### ISSUE TITLE
How to set the chart title

### ISSUE THREAD

**Issue by aguidis** [kirjs/react-highcharts#1]
Hi,

Thanks for this cool component.

I just would like to know how to set a custom chart title. I tried to add a props 'title' or to add a 'title' key in my config object but without success.

**Comment by aguidis** [comment]
My fault I set :
```
title : "my title"
```
instead of :
```
title: {
    text: "Hide default title"
}
```

**Comment by kirjs** [comment]
no worries, good luck with your project
