### ISSUE TITLE
Is there a way to update the chart

### ISSUE THREAD

**Issue by eskimoblood** [kirjs/react-highcharts#10]
Is there a way to update the chart, cause if I understand the code you can only create a new chart. But after that the chart was rendered the first time it should be possible to just update the chart data like this: 

```
chart.series[0].setData(data,true);
```

**Comment by joshhornby** [comment]
+1 I would also like to know this!

**Comment by Kureev** [comment]
In principle, you can just pass new `config` hash to options. In this case component will be re-rendered. But if you want to apply changes in the real time, I'm afraid you need to make a PR for that. They way I see it is move `data` to explicit property and add hook for `componentWillReceiveProps`

**Comment by aldendaniels** [comment]
Addressed in #14.
