### ISSUE TITLE
Reflow highchart after initial display

### ISSUE THREAD

**Issue by kenaniah** [kirjs/react-highcharts#100]
When a chart is displayed inside of a container that has not yet determined its dimensions, it may be improperly sized. This can be fixed by immediately reflowing the chart in the next animation frame. Please add the following code after [chartsFactory.jsx:36](https://github.com/kirjs/react-highcharts/blob/master/src/chartsFactory.jsx#L36):

```javascript
let highchart = this.chart
requestAnimationFrame(function(){
	highchart.reflow()
})
```

**Comment by anmol5varma** [comment]
Where exactly have to place this code snippet?
