### ISSUE TITLE
Plugin Support 

### ISSUE THREAD

**Issue by Stefflan00** [kirjs/react-highcharts#103]
I wonder if there is a plugin support planned for react-highcharts.
I know questions for implementation do not belong here, so i created for the specific case a thread here:
http://stackoverflow.com/questions/35584220/react-highcharts-alignthreshold
Anyways did i miss s.th. or is there no easy way to insert that script for my graphing component.

**Comment by kirjs** [comment]
Hi Stefan, I answered you on stackoverflow. I'm closing the issue for now, feel free to reopen if that didn't work.
