### ISSUE TITLE
HighchartsMore issue

### ISSUE THREAD

**Issue by mspe87** [kirjs/react-highcharts#105]
Im having trouble replicating this example:
http://jsfiddle.net/gh/get/jquery/1.9.1/highslide-software/highcharts.com/tree/master/samples/highcharts/demo/arearange-line/

Im using webpack ProvidePlugin to import global Highcharts:

```
  new webpack.ProvidePlugin({
    Highcharts: "highcharts/highstock"
  })
```
Im adding the libraries to highcharts
```
const highchartsExporting = require('highcharts-exporting'); //export data
highchartsExporting(Highcharts);
const highchartsDrillDownModule = require('highcharts-drilldown'); //drillDown library for highchart
highchartsDrillDownModule(Highcharts);
const highchartsMore = require('highcharts-more');
highchartsMore(Highcharts);
```
and using react-highcharts 
```
var ReactHighcharts = require('react-highcharts');
...
render(){
<ReactHighcharts ref="chart" config={this.getConfig()}> </ReactHighcharts>
}
...

```
getConfig() is returning the config from the example.

The chart is rendered, but the rangearea is only showing the minimum line as shown in the image
![highcharts-more-bug](https://cloud.githubusercontent.com/assets/7411901/13349653/957f0fc4-dc7b-11e5-9d2c-94ee0c4ee6b5.png)
.
Any idea of how to solve this?

**Comment by mspe87** [comment]
Found out that it was a problem with highcharts-mtre package. Solved it by using require('highcharts/highcharts-more') instead

**Comment by vinaykashyap1206** [comment]
@mspe87 How did you import highcharts more in react-highcharts ? I'm facing same issue

**Comment by mspe87** [comment]
Hi.

I did this by importing highcharts-more
and then applying it to a global Highcharts

`import highchartsMore from 'highcharts/highcharts-more';
highchartsMore(Highcharts);
`

When using react-highcharts im now doing:

`const ReactHighcharts = require('react-highcharts').withHighcharts(Highcharts);`

so it is using the instance with highcharts-more applied to it.
Im using version 15, so i dont know if there are changes.
