### ISSUE TITLE
Stock Chart

### ISSUE THREAD

**Issue by joshhornby** [kirjs/react-highcharts#11]
Is it possible to use the Stock chart functionality? 

http://api.highcharts.com/highstock#Highcharts.StockChart

I see in the code it is currently hard coded for ```Chart``` https://github.com/kirjs/react-highcharts/blob/master/src/Highcharts.jsx#L22

**Comment by Kureev** [comment]
That's true, for now it's hardcoded, but you're free to make a PR, we'll appreciate it

**Comment by kirjs** [comment]
Closed by #29
