### ISSUE TITLE
TypeError: Cannot read property '__reactAutoBindMap' of undefined

### ISSUE THREAD

**Issue by isuvorov** [kirjs/react-highcharts#112]
Warning: Something is calling a React component directly. Use a factory or JSX instead.
Uncaught TypeError: Cannot read property '__reactAutoBindMap' of undefined

Using ES6, Babel

**Comment by gfoiani** [comment]
+1

**Comment by isuvorov** [comment]
How I resolve

1) Copy `src/chartsFactory.jsx` to my project in `utils`
2) then
```
import Highcharts from 'highcharts';
import chartsFactory from 'utils/chartsFactory';
const ReactHighcharts = chartsFactory("Chart", Highcharts);
```

Its crutch, but works

**Comment by kirjs** [comment]
Hi Igor/Giovanni, I updated the ReadMe, try doing this: 
```javascript
const ReactHighcharts = require('react-highcharts'); // No need to pass Highcharts here
```

**Comment by kirjs** [comment]
Closing, feel free to reopen, if it haven't solved the issue
