### ISSUE TITLE
Running without Webpack

### ISSUE THREAD

**Issue by borisyankov** [kirjs/react-highcharts#118]
I am having a problem with importing HighCharts/HighStock without webpack.

I am importing HighStock like this
```
import ReactHighstock from 'react-highcharts/bundle/ReactHighstock.src';
```
and then using it like this (amongst other ways)
```
ReactHighstock.Highcharts.setOptions(theme);
```

This works correctly when bundled with webpack.
When ran without it, via mocha, everything still works except the shown import, which does now equal some webpack object.

I really need to run my tests directly without first running through webpack. How can I do that?

**Comment by kirjs** [comment]
Try require maybe instead of import?

**Comment by borisyankov** [comment]
Oh, I forgot to mention it but I also tried require and it seems it worked exactly as 'import', no difference whatsoever.

It took me some time to figure it out, but it is definitely very weird. No other component in a big project exhibited such behavior.

**Comment by kirjs** [comment]
I've added you on hangouts, ping me when you have a sec, and we can debug it together.
As a guess try using non-bundled version.
