### ISSUE TITLE
How do you run both Highcharts and Highmaps in the same application?

### ISSUE THREAD

**Issue by dimamarkus** [kirjs/react-highcharts#124]
I am running React 0.13 and using version 3.0.0 of react-highcharts

Including both Highcharts and Highmaps returns this error
http://www.highcharts.com/errors/16

Ive tried other configurations and importing the files in different combinations but then i end up with 
`Uncaught Error - highmaps.js:144`

**Comment by kirjs** [comment]
I don't remember how exactly it v.3 worked, but my guess would be:
1. Include Highcharts in the codebase
2. Include maps as a module (should be in the modules folder)
3. Use non-bundled versions of ReactHighcharts.

**Comment by dimamarkus** [comment]
Thanks so much for your help. I did get a bit further thanks to your advice. 

Just to confirm, would this be the correct approach? This is what I currently have and the map is rendering as a regular chart. 

```
// LineChart.jsx

// Importing directly from /dist here causes an error asking to include 'highcharts'
// although it is already in the app's js bundle
import ReactHighchart from 'react-highcharts/dist/bundle/highcharts' 

class HighChart extends Component {
  render () {
    return (
      <div id='highchart-container'>
        <ReactHighchart config={...} isPureConfig/>
      </div>
    )
  }
}
------------------------------------------------------------------------------
// MapChart.jsx

// Importing Highmaps here conflicts with the /bundle/highcharts import in LineChart
import ReactHighchart from 'react-highcharts/dist/highcharts'
import Maps from 'react-highcharts/dist/modules/map'

class MapChart extends Component {
  render () {
    return (
      <div id='highchart-container'>
        < ReactHighchart config={...}/>
      </div>
    )
  }
}
`

**Comment by kirjs** [comment]
There should be a way to requre ReactHighmaps, something similar to this:
`var ReactHighmaps = require('react-highcharts/ReactHighmaps');`

**Comment by borisyankov** [comment]
@kirjs I couldn't figure out a way to require a non-bundled version in this manner.

**Comment by kirjs** [comment]
I'm closing the issue, feel free to reopen.

**Comment by tongjun741** [comment]
Uncaught Error: Cannot find module "react-highcharts/ReactHighmaps"

why?

**Comment by kirjs** [comment]
Looks like you're doing something wrong

**Comment by aliceathens** [comment]
I'm also getting the same issue. I have tried all sorts of combinations and variations of trying to include 'ReactHighmaps' no luck.

const ReactHighmaps = require('react-highcharts/ReactHighmaps');

**Comment by kirjs** [comment]
You have to have highmaps in the codebase.

**Comment by wingleungchoi** [comment]
@tongjun741 
i have the same error.
But when i use `import ReactHighmaps from 'react-highcharts/dist/bundle/ReactHighmaps';`, 
it works

**Comment by aliceathens** [comment]
I got it working using:

`const ReactHighmaps = require('react-highcharts/dist/ReactHighmaps');`

But im calling this inside the react render function due to a conflict of loading this in conjunction with non react highcharts pages.
