### ISSUE TITLE
HighchartsMore problem with Meteor 1.3 + React 15.0

### ISSUE THREAD

**Issue by specik** [kirjs/react-highcharts#133]
When trying to include the HighchartsMore module in  Meteor 1.3 + React 15.0 project, I'm getting the dreaded error 17 when trying to create a solidgauge chart. I've tried importing it in various ways to no avail. Any thoughts?

```var ReactHighcharts = require('react-highcharts');
var HighchartsMore = require('highcharts-more');
HighchartsMore(ReactHighcharts.Highcharts)```

```Error: Highcharts error #17: www.highcharts.com/errors/17
    at Error (native)```

**Comment by specik** [comment]
Managed to find a solution. Not sure if this is something specific to my setup but the only way I got the solidgauge chart type to work is by requiring it as follows:

```javascript
const ReactHighcharts = require('react-highcharts');
const HighchartsMore = require('highcharts-more');
const SolidGauge = require('highcharts/modules/solid-gauge')

HighchartsMore(ReactHighcharts.Highcharts)
SolidGauge(ReactHighcharts.Highcharts)
```

**Comment by gnudle** [comment]
Thanks! This worked for me too...
