### ISSUE TITLE
Highcharts from a external (non-required) source

### ISSUE THREAD

**Issue by zediah** [kirjs/react-highcharts#137]
I've got a situation where I've got to rely on highcharts already being defined on the page from outside my compiled source (I'm using grunt + browserify) and I get errors saying highcharts is already defined when using this module. 

I thought I'd be able to get it to work with browserify-shim but I can't seem to find the correct setup for it. Previous versions of this module would assume you were including your own 'Highcharts' global or use the bundled version so I didn't need to try shim anything until now. The new version has changed and seems to no longer allow you choose which assumption to take.

Does anyone have a solution for this? Either correct browserify-shim settings or a way for react-highcharts to not assume an imported highcharts. I could be asking a dumb question here and be missing something obvious, if so, please also point this out me!

**Comment by kirjs** [comment]
How exactly do you use it?

**Comment by zediah** [comment]
I'll try give what setup I can think of...
I've manually removed 'highcharts' from node_modules that react-highcharts requires. I did this because if it's there react-highcharts requires it and I get a duplicate defined highcharts error. What I am trying to do is have it take my global version of it. 
I'm importing react-highcharts via 
`"import HighChartElement from "react-highcharts"" `
I'm running es2015 react with classes/import statements etc
I'm compiling everything via grunt commands + grunt-browserify + babel with following command:
```
 browserify: {
      build: {
        files: {
          "bundle.js": jsFileList,
        },
          transform: [['babelify', {presets: ["es2015", "react"]}]],
        },
      },
```
But I have the browserify-shim in my package.json (as it suggests) to try shim in highcharts with no success:
```
 "browserify-shim": {
    "highcharts": "global:Highcharts"
    
  },
  "browserify": {
    "transform": [
      ["browserify-shim", { "global": true}]
    ]
  },
```

I'm not sure there's anything else related to it that I can show.

**Comment by kirjs** [comment]
Let me know if you still need help with this, I'll ping you on gchat, and we'll figure it out.

**Comment by cnaut** [comment]
What was the resolution to this? I am having a similar issue

**Comment by NEtOrnANtHeR** [comment]
Similar issue +1. 
How did you make using highcharts as an external source work as last?

**Comment by kirjs** [comment]
I'd say try requiring 
https://github.com/kirjs/react-highcharts/blob/master/src/chartsFactory.jsx 
and passing your Highcharts instance like here:  
`https://github.com/kirjs/react-highcharts/blob/master/src/ReactHighcharts.jsx`.

**Comment by zediah** [comment]
So sorry about never getting in contact with you or replying. 

In regards to my 'solution', I just reverted to a previous version of react-highcharts where it worked... not a great solution I know!
