### ISSUE TITLE
About the chart animations ?

### ISSUE THREAD

**Issue by be-next-hotdog** [kirjs/react-highcharts#142]
Heyya guys,

I had a try to generate a 3D Donut chart but the plugin rendered immediately without any animation. So I need a module in additional ? 

Thx a lot.

**Comment by be-next-hotdog** [comment]
No one met the prob as mine ?

**Comment by kirjs** [comment]
See if setting `neverReflow` to true would work for you

**Comment by be-next-hotdog** [comment]
I found no option called neverReflow.
If you meant "reflow" to false, unfortunately it still doesn't work for me.

**Comment by kirjs** [comment]
https://github.com/kirjs/react-highcharts/blob/master/src/chartsFactory.jsx#L11

**Comment by kirjs** [comment]
Please let me know if this worked for you

**Comment by kirjs** [comment]
Feel free to reopen

**Comment by be-next-hotdog** [comment]
So sorry for coming late, but this props was never gonna work for me.
Finally, I wrote my own components to implement highchart.

**Comment by jordancardwell** [comment]
@be-next-hotdog (or others in the future) you may try this workaround we used here 
https://github.com/kirjs/react-highcharts/issues/171

hope it helps someone out 👍
