### ISSUE TITLE
TypeError: Cannot read property 'xAxis' of undefined

### ISSUE THREAD

**Issue by rarius** [kirjs/react-highcharts#144]
I'm using the ReactHighstock component, I get "Uncaught TypeError: Cannot read property 'xAxis' of undefined" on render.  Highcharts module version was 4.2.5, I downgraded to 4.2.4 and it worked fine.

**Comment by kirjs** [comment]
Seems like Highcharts bug then?

**Comment by kirjs** [comment]
Feel free to reopen
