### ISSUE TITLE
update highcharts to 4.2.5

### ISSUE THREAD

**Issue by mblakele** [kirjs/react-highcharts#145]
I'm interested in https://github.com/highcharts/highcharts/commit/231af1d4e63c54cc728fe61a3daf59e77c1981f7 because I think it will fix a problem with columnrange charts and axis breaks. Thanks!

**Comment by kirjs** [comment]
Hi Michael, 

I'll do the update around this weekend. 
Meanwhile consider using non-bundled version of react-highcharts which can be used with any version of highcharts.

**Comment by mblakele** [comment]
I think I am using the non-bundled version: does this look right? I have 2.4.5 installed via npm.

```
global.Highcharts = require('highcharts')
require('highcharts/../modules/broken-axis')
require('highcharts-more')(global.Highcharts)

const React = require('react')
const ReactHighcharts = require('react-highcharts')
...
```

It's also possible that I'm hitting a bug in 2.4.5, but I found https://github.com/highcharts/highcharts/issues/4868 and decided that was the most likely culprit.

**Comment by kirjs** [comment]
This seems like about right, which Highcharts version do you get in the browser?

**Comment by mblakele** [comment]
Just getting back to this: I seem to be using 4.2.5 after all, so the problem must be elsewhere.

```
console.debug('using Highcharts', Highcharts.version)
=> using Highcharts 4.2.5
```

**Comment by mblakele** [comment]
I wasn't passing Highcharts when requiring the broken-axis module. With that change and using 4.2.5, columnrange breaks are working.

```
global.Highcharts = require('highcharts')
require('highcharts/../modules/broken-axis')(global.Highcharts)
require('highcharts-more')(global.Highcharts)

const React = require('react')
const ReactHighcharts = require('react-highcharts')
...
```

**Comment by kirjs** [comment]
So does it work now? Feel free to reopen the issue.
