### ISSUE TITLE
Rendering react-highcharts on node

### ISSUE THREAD

**Issue by jachinte** [kirjs/react-highcharts#147]
Hello,

I'm using React with webpack and express. I already read [Rendering react-highcharts on node](https://github.com/kirjs/react-highcharts/blob/master/recipes.md#rendering-react-highcharts-on-node), however I don't undarstand how to achieve it. Can you please give me a hint on doing this?

This is my basic `Chart` component:
```javascript
import React, {Component} from 'react';
import ReactDOM from 'react-dom';
import Highcharts from 'react-highcharts/src/fakeHighcharts.js';
import ReactHighcharts from 'react-highcharts';
class Chart extends Component {
	constructor(props) {
		super(props);
	}
	render() {
		const config = {
			xAxis: {
				categories: ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec']
			},
			series: [{
				data: [29.9, 71.5, 106.4, 129.2, 144.0, 176.0, 135.6, 148.5, 216.4, 194.1, 295.6, 454.4]
			}]
		};
		return (
			<ReactHighcharts config={config}></ReactHighcharts>
		);
	}
}
export default Chart;
```
However, in the browser I get this error: `Uncaught TypeError: e[t] is not a constructor`, referring to [chartsFactory.jsx#L24](https://github.com/kirjs/react-highcharts/blob/master/src/chartsFactory.jsx#L24).

Do I have to load Highcharts in the browser?:
```html
<script src="https://code.highcharts.com/highcharts.js"></script>
````
If I do it right now, I'll get this error: `highcharts.js?c89c:8Uncaught Error: Highcharts error #16: www.highcharts.com/errors/16` (already defined).

I'm using react `15.0.2`, react-highcharts `8.3.2` and highcharts `4.2.5`. Thanks!

**Comment by kirjs** [comment]
In this case you'll have to configure your module loader to provide fakeHighcharts instead of Highcharts when running on node.

**Comment by jachinte** [comment]
Thanks!
