### ISSUE TITLE
Stacked Bar Chart custom attributes?

### ISSUE THREAD

**Issue by davidfloegel** [kirjs/react-highcharts#150]
Hi,

I'm having a stacked bar chart, and on hover I want a list of names to appear in the tooltip.

I found a solution that works with jquery / pure javascript but it somehow doesn't in react.

in my data array I have something like:
```
{
                names: ['Test, Test, Test'],
                name: d.name,
                data: this.calculateForDescriptor( d ),
                color: d.color
}
```

And my tooltip formatter:

```
tooltip: {
                formatter: function() {
                    var result = `Names`;
                   // in here I can't access the names attribute, but every other attribute.
                    return result;
                }
},
```

Any idea why I can't access the names attribute?

Thanks a lot!
David

**Comment by kirjs** [comment]
Hi David, do you still need help with this?

**Comment by kirjs** [comment]
Feel free to reopen

**Comment by rizkiandrianto** [comment]
Any solution guys @kirjs @davidfloegel

**Comment by paufabregat** [comment]
I found the solution to this mentioned in a couple of issues from the highcharts repo: 
https://github.com/highcharts/highcharts/issues/5263
https://github.com/highcharts/highcharts/issues/4258
In short, disable `dataGrouping`! Hope it helps @rizkiandrianto

**Comment by rizkiandrianto** [comment]
Thanks @paufabregat will check it later...
