### ISSUE TITLE
Any Examples of Synchronized Charts?

### ISSUE THREAD

**Issue by joshburgess** [kirjs/react-highcharts#151]
Are there any examples of synchronizing chart events across multiple charts using react-highcharts?

Here are some examples, but using the old jQuery style API for highcharts...

[http://www.highcharts.com/demo/synchronized-charts](http://www.highcharts.com/demo/synchronized-charts)

[http://jsfiddle.net/7Lhsb00g/](http://jsfiddle.net/7Lhsb00g/)

**Comment by kirjs** [comment]
This is how you can access the chart instance in a wrapping component. 
https://github.com/kirjs/react-highcharts#accessing-highcharts-api-after-render

Alternatively you should be able to use Highcharts.charts list.

**Comment by kirjs** [comment]
I'll close the issue, but feel free to reopen if you still need help with it

**Comment by yashshah** [comment]
Hi @joshburgess, were you able to get synchronized charts through the library?

I tried with Highcharts.charts list but that does not work. It might be due to state variable might be overriding it.

**Comment by ardok** [comment]
I'm trying to do this as well. It seems really complicated with react since there is no exposed "Highcharts" global variable?
I might be wrong, but this would mean that you need to store all the charts in your class variable using the `afterRender`.
Can't use state because `setState` is async.

**Comment by ardok** [comment]
Ok, in case anyone is looking into this, this is what I do (my charts have multiple series):
```
function hcContainerBind(charts, e) {
  charts.forEach((chart) => {
    // Find coordinates within the chart
    e = chart.pointer.normalize(e);
    const points = [];

    chart.series.forEach((series) => {
      const p = series.searchPoint(e, true);

      if (p) {
        // This is the point index that we get from `searchPoint` method above
        const closestPointIdx = p.index;
        
        // This is to get the actual x-axis index
        const actualColIdx = Math.round(chart.xAxis[0].toValue(e.chartX));

        // Only push if the point index from searchPoint is the same as the rounded `toValue`
        if (p.x !== null && p.y !== null && closestPointIdx === actualColIdx) {
          points.push(p);
          // p.onMouseOver();
        }
      }
    });

    if (points.length > 0) {
      // Show the tooltip
      chart.tooltip.refresh(points);
      // Show the crosshair
      chart.xAxis[0].drawCrosshair(e, points[0]);
    } else {
      chart.tooltip.hide();
    }
  });
}
```

In my wrapper component, I have this as well that will get called for every chart render (utilizing `afterRender`:
```
  bindContainers() {
    const hcContainers = document.getElementsByClassName('hc-container');
    const bindedFunc = hcContainerBind.bind(null, this.charts);
    [].forEach.call(hcContainers, (el) => {
      el.onmousemove = el.ontouchmove = el.ontouchstart = bindedFunc;
      el.onmouseout = this.hideTooltips;
    });
  }
```

**Comment by ReactRS** [comment]
I am working with React and HighCharts. I am relatively new to both these technologies. I need to generate two synchronized HighStock charts. I was able to display the charts with the below layout.

<div class=container>
<div class=chart1>new highcharts.StockChart(newChartOptions) </div>
<div class=chart2>new highcharts.StockChart(newChartOptions)</div>
</div> 
The Charts are displayed. I want to synchronize the charts to have a common tool tip, I see the http://www.highcharts.com/demo/synchronized-charts , not sure how to implement with React. I have tried to assign a function(handleEvent(e)) to plotOptions:{line:{ point:{ event:{click: and MouseOver}}}} but it did not help. Not sure how to invoke the handleEvent(e) method. I am not sure how/when to invoke the handleEvent(e). Any help is greatly is appreciated.

Below is the Component code:

import $ from 'jQuery';
import React from 'react';
import highcharts from 'highcharts-release/highstock';

export default class SynchronizedStatusChart extends React.Component {

    constructor (props) {
        super(props);
        this.state = {
            chartName: `chart${this.props.chartNum}`,
        };
    }

 handleEvent(e){

        let allCharts = highcharts.charts;
        console("SynchronizedStatusChart:handleEvent:ChartsLength = " + allCharts.length);
        var chart, point, i, event;


        for (i = 0; i < allCharts.length; i = i + 1)
        {
            chart = highcharts.charts[i];
            event = chart.pointer.normalize(e.originalEvent); // Find coordinates within the chart
            point = chart.series[0].searchPoint(event, true); // Get the hovered point
            if (point) {
                this.onMouseOver(); // Show the hover marker
                this.series.chart.tooltip.refresh(this); // Show the tooltip
                this.series.chart.xAxis[0].drawCrosshair(event, this);
            }
        }
    }


   componentDidMount () {

    }


    componentWillUpdate (nextProps) {
        for(let i=0; i<nextProps.data.length; i++){
           this.generateChart(nextProps.data[i],i+1,nextProps.titles[i]);
       }  
     }

    generateChart(data, i, title) {
        if(data == null)
        {
            data = [];
        }

        let ticksData = [0,1];
        let newChartOptions =
            {
                chart: {
                    //renderTo: document.getElementById(this.state.chartName),
                    renderTo: document.getElementById(`SyncChart${i}`),
                    height:'125'
                },
                rangeSelector: {
                    enabled: false
                },
                credits: {
                    enabled: false
                },
                navigator: {
                   enabled: false
                },
                scrollbar: {
                    enabled: false
                },
                tooltip: {
                    shared: true,
                    pointFormat: '<span style="color:{series.color}">{series.name}</span>: <b>{point.y:.2f}</b> <br/>'
                },
                xAxis:{

                },
                yAxis: {
                    offset: 15,
                    labels: {
                        align: 'center',
                        x: -3,
                        y: 6  
                    },
                    tickPositioner: function () {
                        var positions = ticksData;
                        return positions;
                    },
                    opposite:false,
                    showLastLabel: true,
                    title:{
                        text:title
                    }
                },
                series: [{
                    name: title,
                    type: this.props.status ? 'area' : 'line',
                    data: data,
                    showInNavigator: false

                }],
       };
        new highcharts.StockChart(newChartOptions);
    }


render () {

    return (
      <div className="med-chart col-md-9" id={this.state.chartName} style={this.props.chartStyle}> 
         <div id='SyncChart1'></div>
         <div id='SyncChart2'></div>
     </div>
    );
  }


}
