### ISSUE TITLE
How to set global options - utcOffset and lang?

### ISSUE THREAD

**Issue by skylinezum** [kirjs/react-highcharts#153]
I'm localizing my site and I see on highcharts API that I can use momentjs and utcOffset to localize the time. But what is the interface for setting global options in React-Highchrats?

Thanks!

**Comment by kirjs** [comment]
It depends on your setup, but shouldn't really differ from the way you would do without react-highcharts

**Comment by skylinezum** [comment]
@kirjs  Based on the highcharts api, it seems rather difficult to dynamically change the timezone with a prop. Have you ever run into a similar situation that necessitates changing utcOffset? and how were you able to solve it. Thanks.

**Comment by kirjs** [comment]
Can you show me how you would normally do the same without react-highcharts?

**Comment by skylinezum** [comment]
i've never used highcharts before, so I don't know how to do this with highcharts :p

**Comment by kirjs** [comment]
If you solved this, posting the solution would help other users.

**Comment by skylinezum** [comment]
Didn't solve it. Just offset the timestamp in the data itself. Not an ideal solution, but if I figure something out. I'll post a solution. 👍

**Comment by shsethi** [comment]
I wrote a small function and called it before rendering 
``` setTimeZone(timezone) {
    let offset = timezone == 'local' ? (new Date()).getTimezoneOffset() : 0;
    ReactHighcharts.Highcharts.setOptions(
      {
        global: {
          timezoneOffset: offset
        }
      });
  }```

**Comment by kirjs** [comment]
@shsethi Thanks for the solution!
