### ISSUE TITLE
Language options not accessible

### ISSUE THREAD

**Issue by jesperwiner** [kirjs/react-highcharts#154]
Highcharts need this on global, see: http://api.highcharts.com/highcharts#lang

I messed around and just added it as extra param to renderChart.
Loading the lang object and sending it in as extra prop.
It works, but not sure this is the preferred way to do it.

```javascript
    renderChart: function (config, language){
      if (!config) {
        throw new Error('Config must be specified for the ' + displayName + ' component');
      }

      // Need to apply language before chart is created.
      if (language) {
        Highcharts.setOptions(language);
      }

      let chartConfig = config.chart;
      this.chart = new Highcharts[chartType]({
```

```javascript
    componentDidMount: function (){
      this.renderChart(this.props.config, this.props.language);
    },
```

**Comment by kirjs** [comment]
Why not `ReactHighcharts.Highcharts.setOptions(language)` in whenever you bootstrap your app?

**Comment by jesperwiner** [comment]
Your way works fine when I try in the demo. Ran into this issue I guess due to the way we wrapped it and couldn't access Highcharts like that. Now I have rewritten it to ES6 anyway and this no longer applies.
