### ISSUE TITLE
Problems with reflow

### ISSUE THREAD

**Issue by alfonsomunozpomer** [kirjs/react-highcharts#155]
We have a React Highcharts component in our project and it all works well, but because we’re using Bootstrap tabs, whenever we switch to a tab containing a chart its size is set to the default (600×400) until the window is resized.

I have the following component:
```
componentDidMount: function () {
    var heatmap = this.refs.chart.getChart();
    this.refs.container.addEventListener("gxaReflowHeatmap", function(e) {
        heatmap.reflow();
    });
}
...
render: function() {
    ...
    return (
            <div>
                <div className="highcharts_container" ref="container">
                    <ReactHighcharts config={highchartsOptions} ref="chart" isPureConfig={true}/>
                    {barcharts_legend}
                </div>

            </div>
    );
}
```
However, every time I send the `gxaReflowHeatmap` event to force-reflow the chart, I get the following in the JS console:
```
TypeError: b.options is undefined
```

Is there any known issues with `reflow()`? Are we doing something wrong? Any help appreciated!

**Comment by kirjs** [comment]
Can you check out what's the `heatmap` contents are when you get the error?

**Comment by alfonsomunozpomer** [comment]
Thank you for the early reply. We’re a bit burdened with a release this week, but I’ll get back next week and let you know.

Thanks for the interest and for the great work!

P.S.: After this week’s release you’ll be able to see our React Highcharts in production. ;)

**Comment by kirjs** [comment]
That's awesome, good luck with the release, let me know when you have any updates.
