### ISSUE TITLE
setOptions not working if using Highstock

### ISSUE THREAD

**Issue by ecjs** [kirjs/react-highcharts#157]
I am not sure if this is default behavior:
If you are using a Highstock chart, and trying to use:

`Highcharts.setOptions({
  global: {
    useUTC: false,
  }
});`

It doesn't actually change any of those options, at least when trying to set useUTC.

In order to get this to work, I had to use this:
`ReactHighstock.Highcharts.setOptions({
  global: {
    useUTC: false,
  }
});`

**Comment by ecjs** [comment]
Also, I tried in the demo, and it wasn't setting useUTC there either.

**Comment by kirjs** [comment]
I assume in your example `ReactHighstock` is using a different `Highcharts` instance than your other script. 
This is not always the case, and mostly depends on your build setup.

**Comment by kirjs** [comment]
[Now you can pass the Highcharts instance manually](https://github.com/kirjs/react-highcharts#passing-highcharts-instance-manually)

**Comment by kirjs** [comment]
Feel free to reopen

**Comment by tquetano-r7** [comment]
@kirjs I'm trying this new technique ... but it's failing with the error `ReactHighcharts.js?7d57:1Uncaught TypeError: i[e] is not a constructor`. My code:

```javascript
const Highcharts = window.Highcharts || require('react-highcharts/dist/ReactHighstock.src');

const ReactHighcharts = require('react-highcharts').withHighcharts(Highcharts);
```
