### ISSUE TITLE
Error 17 flags

### ISSUE THREAD

**Issue by mspe87** [kirjs/react-highcharts#158]
Hi. First of all, thank you for porting this to react!

Im having an issue after upgrading from 7.0.0 to 8.3.3 where im getting error 17 (series type not found) when trying to render flags in highchart. 
Flag series belong to Highstock, but they can also be applied to a regular Highcharts chart created with the Highcharts.Chart() constructor as long as the highstock.js file is loaded in the page.

Ive included Highchart globaly and if i console.log it in the class where i'm tring to render the flags i can see that Higcharts variable has key product with value of "Highstock". So it is using highstock.

Any ideas?

**Comment by kirjs** [comment]
Hi Mads, 
Does it work if you use ReactHighstock component?

**Comment by mspe87** [comment]
Hi Kirill.

Sorry for my late reply. Yes, then it works. Any idea of why it breaks when using ReachHighcharts?

**Comment by kirjs** [comment]
https://github.com/kirjs/react-highcharts/blob/master/src/Highstock.jsx

**Comment by kirjs** [comment]
Highstock requires different Highcharts instance, so can do something like:
```jsx
var ReactHighcharts = require('./chartsFactory.jsx')('Chart', SharedHighchartsInstance);
var ReactHighstock = require('./chartsFactory.jsx')('StockChart', SharedHighchartsInstance);
```
Instead of using provided ones.

**Comment by mspe87** [comment]
This works. Though maybe it should be possible to assign Highcharts instance when creating ReactHighcharts ie: var ReactHighcharts = require('react-highcharts')(Highcharts); ?

**Comment by kirjs** [comment]
[https://github.com/kirjs/react-highcharts#passing-highcharts-instance-manually](Now it's possible)

**Comment by mspe87** [comment]
Looks pretty cool! will test it tommorow. thank you
