### ISSUE TITLE
.withHighcharts is not working as advertised

### ISSUE THREAD

**Issue by tquetano-r7** [kirjs/react-highcharts#160]
I'm trying the new `.withHighcharts()` technique ... but it's failing with the error `ReactHighcharts.js?7d57:1Uncaught TypeError: Cannot read property 'requestAnimationFrame' of undefined`. My code:

```javascript
const Highcharts = window.Highcharts || require('highcharts/highstock');

const ReactHighcharts = require('react-highcharts').withHighcharts(Highcharts);
```

Any help here would be much appreciated.

**Comment by tquetano-r7** [comment]
So a little more digging ... looks like `global` in `chartsFactory.jsx` is never defined as anything (window, node global, etc.), which is causing the above error. I know this because this works:

```javascript
const ReactHighcharts = require('react-highcharts/src/chartsFactory')('Chart', Highcharts);
```

and that is once I changed this:

```javascript
      if (!this.props.neverReflow) {
        window.requestAnimationFrame && requestAnimationFrame(()=>{
          this.chart && this.chart.options && this.chart.reflow();
        });
      }
```

Before, it was using global.requestAnimationFrame.

**Comment by kirjs** [comment]
Hi Tony, thanks a lot for the research. 
Feel free to PR this in, or I'll fix it later this week.

**Comment by tquetano-r7** [comment]
As requested, PR created. Pretty simple, coalescing `global` and `window` to a scoped `win` variable, which is then referenced when checking `requestAnimationFrame`. Passed all tests locally.
