### ISSUE TITLE
Routing and ReactHighcharts

### ISSUE THREAD

**Issue by unski11ed** [kirjs/react-highcharts#162]
Hi

I have a React app with redux and ReactRouter attached. 

When i start the page, the first chart displays ok, but when i go to a different page, with some other type of chart it gets messed up. The configs of the first and the second charts are mixed, which is supposedly caused by the spread operator used in `chartsFactory.jsx`, and the fact that React Router doesn't unmount components on page switching. 

What would be the best solution here? Keeping detailed configs for every chart, so that they will always override the previous? Forcing dismounts? Or maybe there is something I'm missng here

**Comment by kirjs** [comment]
Please let me know what the solution was.

**Comment by unski11ed** [comment]
There was a problem somewhere else (duh). I used `sindresorhus/deep-assign` for merging a couple of chart setting bits. I was 100% sure it was compatible with ES2015 object.assign, but it turned out it is modifying the source objects as well...

Sorry for the most stupid spam, I have panicked a little.

**Comment by kirjs** [comment]
Thanks, no worries, maybe it'll help someone
