### ISSUE TITLE
Is there a way to use renderTo from containing component

### ISSUE THREAD

**Issue by bpote** [kirjs/react-highcharts#163]
I am trying to achieve something like below:
```
render (
<div id='container'><ReactHighmaps config={this.state.config}></div>
)
```

This I think would not work because `ReactHighmaps` scope does not know about containing element as far as I know. Any thoughts on this?

**Comment by kirjs** [comment]
Not sure I understand.
Do you want the chart to be attached to the div you provide instead of creating an inner element?

**Comment by Brightergy-BrishaPote** [comment]
@kirjs yeah, that's true. I want to do something like:
```
chart: {
  renderTo: '#container'
}
```
I already did my workaround but I was basically try to achieve what I've described in https://github.com/highcharts/highcharts/issues/5450

**Comment by kirjs** [comment]
I guess I `ReactHighcharts` could take a `wrapper-id` property or something, but would would be the use case for it?

**Comment by Brightergy-BrishaPote** [comment]
@kirjs yeah it could be but probably it needs to be a DOM element. Not sure how highcharts renders. Like not sure if it requires actual DOM ready or can just insert in the DOM node even without having to render it.

**Comment by kirjs** [comment]
I'm still having a hard time understanding the use case for that.

**Comment by Brightergy-BrishaPote** [comment]
@kirjs My main problem right now is I'm trying to render 3 different highchart components in a single page. For this, I've a GraphContainer which basically takes socket URL and type of graph to render and once the data is fetched, it renders another component which performs rendering of the actual highcharts component. In this flow, it seems that none of the 3 charts know about each other's existence and hence there are duplicate IDs (such as `highcharts-0` or `highcharts-1`) which are randomly duplicates.

```
<!-- the clipPath from first chart -->
<clipPath id="highcharts-1">
<!-- snipped -->
<!-- the linearGradient from third chart -->
<linearGradient id="highcharts-1" x1="0" y1="1" x2="0" y2="0">
```

Somewhere in the DOM, the ID is referenced in a way like `url(#highcharts-1)` and it is supposed to use linearGradient but ends up using clipPath. I'm also wondering there could be some alternative pattern to address.

Below is my initial render which calls Graph component. The Graph component is a wrapper that performs websocket connection, gets data and then renders the appropriate chart based on type.
```
return (
      <div className='content'>
        <div className='chart'>
          <Graph token={this.props.token} selection={this.state.selection} range="week" socket_url={this.props.socket_url} channel="analyze:power" />
        </div>
        <div className='chart'>
          <Graph token={this.props.token} selection={this.state.selection} range="week" socket_url={this.props.socket_url} channel="analyze:demand" />
        </div>
        <div className='chart'>
          <Graph token={this.props.token} selection={this.state.selection} range="7-days" socket_url={this.props.socket_url} channel="analyze:heatmap" chartType="heatmap" />
        </div>
    </div>
```

**Comment by kirjs** [comment]
Sorry I'm having a hard time trying to understand what you're trying to do. 
You should be able to set container ID just by specifying it as a property: 
`<ReactHighcharts id = {id}`.

Making sure the ids are unique seems to  be outside of scope of react-highcharts.

Good luck with your project, feel free to reopen if I misunderstood.
