### ISSUE TITLE
react 15.2 unsupported attribute to div

### ISSUE THREAD

**Issue by eMerzh** [kirjs/react-highcharts#164]
hi, 
i tried to update react and got a bunch of errors.
the new version of react doesn't support giving extract props to elements like "div".
the error look like

> 
> Warning: Unknown prop `config` on <div> tag. Remove this prop from the element. For details, see https://fb.me/react-unknown-prop
>     in div (created by HighchartsChart)
>     in HighchartsChart (created by Chart)

**Comment by kirjs** [comment]
Thanks, 
The change seems pretty trivial, please create a PR if you have a spare minute.
Otherwise I'll fix it in the next couple of weeks (I'm travelling ATM, setup may take a while).

**Comment by eMerzh** [comment]
ok, i tried to make the change.. not really sure about it, but it seems to not do the error anymore

**Comment by tquetano-r7** [comment]
@kirjs created the PR, seemed pretty straightforward to use destructuring + rest to remove the internal props. I based the values removed off of what was called out in propTypes, but if I missed any others let me know and I'll update.

**Comment by tquetano-r7** [comment]
@eMerzh ur fix solves the problem, but breaks the ability to pass any additional props (`className`, `style`, etc) to the div for the chart. That's why I submitted the additional PR ... solve the breakage, but don't prevent the flexibility that existed prior.

**Comment by eMerzh** [comment]
Cool, @tquetano-r7 :) hope this can be merged soon :)

**Comment by kirjs** [comment]
This should be fixed I assume?
