### ISSUE TITLE
can't use highcarts with highstock together

### ISSUE THREAD

**Issue by MarloweW** [kirjs/react-highcharts#166]
Use highcharts with highstock will report error:

```
highstock.js:8 Uncaught Error: Highcharts error #16: www.highcharts.com/errors/16
```

**Comment by kirjs** [comment]
How do you use it?
This may help: https://github.com/kirjs/react-highcharts#passing-highcharts-instance-manually

**Comment by MarloweW** [comment]
I am using high charts in one page, and trying to use high stock in another.
Passing instance manually seems helpful, I'll try later when I am with my laptop.

**Comment by MarloweW** [comment]
This is the usage:

component A:
```
import Highcharts from 'react-highcharts';
....

<Highcharts config.../>
```

component B:
```
import ReactHighstock from 'react-highcharts/dist/ReactHighstock';
<ReactHighstock .../>
```
tried passing-highcharts-instance-manually, got same error.

**Comment by kirjs** [comment]
Try using ReactHighstock for both

**Comment by kirjs** [comment]
Feel free to reopen
