### ISSUE TITLE
Pie Chart error

### ISSUE THREAD

**Issue by rolandsusans** [kirjs/react-highcharts#17]
I have implemented my compnent in following way: 

```javascript 

var React = require('react');
var HighCharts = require('react-highcharts');
var Theme = require('../settings/Theme');

var HighChartsComponent = React.createClass({

    componentWillMount: function(){
        this.setTheme();
    },

    getChart: function(){

      if(this.refs.chart != undefined){
          return this.refs.chart.getChart();
      }else {
          throw new Error('Chart is only available when chart didMount');
      }
    },

    /**
     * This method sets theme to Highcharts
     */
    setTheme: function () {
        HighCharts.Highcharts.theme = Theme;
        HighCharts.Highcharts.setOptions(HighCharts.Highcharts.theme);
    },


    render: function () {
       return (
           <HighCharts
               config={this.props.data}
               ref={"chart"}
               style={{width: '100%', height: '100%', position: 'absolute'}}
               />
       );
    }
});

module.exports = HighChartsComponent;
```

Other chart types, like - area, column, etc is working fine, but when i try to implement following pie chart demo http://www.highcharts.com/demo/pie-legend, chart is not rendered at all, although it have received props : 
![error](https://cloud.githubusercontent.com/assets/6154604/9177438/dceeea5c-3f99-11e5-998d-a4ce8bb569e7.png)

What i'm doing wrong, or what can cause the problem?

**Comment by kirjs** [comment]
Hi Roland, 

I actually was able to display the pieChart. 
You can see an example in this branch: 
https://github.com/kirjs/react-highcharts/blob/issue-17/demo/issue17/app.jsx

Are there any console errors you're getting?

**Comment by rolandsusans** [comment]
Hi, no, no console errors, only difference between your example and mine, is that you have hard encoded config for pie chart, in mine example, i'm getting config from ajax request, so i think that's why something is not working properly. On server side i'm using  https://github.com/ghunti/HighchartsPHP.

I tested your example and it works as it's supposed to work. Will let you know about progress.

**Comment by rolandsusans** [comment]
Ohh, my bad. **Series should always bee array**
 I had : 
``` javascript
series: {
    name: "Brands",
    colorByPoint: true,
    data: [{
      name: "Microsoft Internet Explorer",
      y: 56.33
    }, {
      name: "Chrome",
      y: 24.03,
      sliced: true,
      selected: true
    }, {
      name: "Firefox",
      y: 10.38
    }, {
      name: "Safari",
      y: 4.77
    }, {
      name: "Opera",
      y: 0.91
    }, {
      name: "Proprietary or Undetectable",
      y: 0.2
    }]
  }
```
but now, after hard debug,  i have : 

```javascript

series: [{
    name: "Brands",
    colorByPoint: true,
    data: [{
      name: "Microsoft Internet Explorer",
      y: 56.33
    }, {
      name: "Chrome",
      y: 24.03,
      sliced: true,
      selected: true
    }, {
      name: "Firefox",
      y: 10.38
    }, {
      name: "Safari",
      y: 4.77
    }, {
      name: "Opera",
      y: 0.91
    }, {
      name: "Proprietary or Undetectable",
      y: 0.2
    }]
  }]
```

Interesting that there was no error in console, about that series should be array, not object.

**Comment by kirjs** [comment]
Well, glad you figured it out. 

Might be worth checking with the highcharts guys on why no error is shown, but that might be consistent with the way they handle errors.
