### ISSUE TITLE
isPureConfig Not Working for Me

### ISSUE THREAD

**Issue by joshburgess** [kirjs/react-highcharts#172]
Hi, it seems that isPureConfig isn't actually working. I'm even observing state changes with Redux, and there was 0 state change while still getting a rerender. My config is a mostly static object where only the data points for each series are updated via passed down props mapped from the redux store... However, I'm getting extra rerenders in highcharts before I actually get any new data that affects the props passed to ReactHighcharts.

I tested out neverReflow, and that actually does work.... but then that prevents actual state changes from triggering rerenders too, which is a worse problem.

Any ideas?

**Comment by joshburgess** [comment]
Nevermind, it appears I solved my problem... had to mark the component as pure while also using isPureConfig (I'm doing so via the "pure" HoC in the recompose library.) I didn't realize that was required.

**Comment by kirjs** [comment]
This seems like a legit issue?
Can you elaborate a bit on what worked for you?

**Comment by joshburgess** [comment]
Ok, so here's more detail:

Instead of using ReactHighcharts directly in my view component, I've chosen to abstract this out to a separate component, that looks like this:

```
const ReactHighchartsLineChart = ({ data, title }) => { 
 // define chart config here
 const config = { ... } 
  // this is mostly static/hard-coded, except for the chart title & series data properties
  // which are based on mapping over the data and returning arrays of specific properties

  // then, the only other thing it does is return the rendered component
  return <ReactHighcharts config={config} isPureConfig />
 }
```

The purpose of this was to make working with ReactHighcharts easier to manage in a project that uses Redux to handle all state. Using this method, the component only needs to update based on getting a new set of data or a new title, and this wrapper component, itself, creates the new config object to pass to ReactHighcharts. This means I don't have to deal with trying to keep this config object in my Redux store's state, which helps avoid awkwardly merging in new data to the config object. I think it's a better API to work with from the outside.

Anyway, it seems to me that the reason for my problem was that isPureConfig probably does not work when it has a wrapper component like this, unless that wrapper component is also marked Pure by using something like the PureRenderMixin or the Pure higher order component/decorator found in the Recompose library.

I was already using Recompose for various things, so I made the wrapper component pure, and then isPureConfig seemed to start working as intended. Here is the code that does that:

```
const enhance = compose(
  setPropTypes({
    data: PropTypes.array.isRequired,
    title: PropTypes.string.isRequired,
  }),
  pure
)

export default enhance(ReactHighchartsLineChart)
```

Although, something odd about this is that I did not have to do anything to the wrapper component when giving ReactHighcharts the neverReflow prop...

Hopefully that's enough info. Let me know if you have any questions.

**Comment by joshburgess** [comment]
It looks like I'm having issues with isPureConfig again now. If I pass a clickHandler function to the wrapper component described above, it causes a rerender every single time any property changes even if the function itself hasn't changed at all and the changed property isn't being used by this component........ The wrapper function is marked pure and the ReactHighcharts component is using isPureConfig, exactly like described above. It just doesn't work...

**Comment by kirjs** [comment]
Any chance you could reproduce in [jsbin](http://qs.js.org/jsbin/react-highcharts?autostart)?

**Comment by joshburgess** [comment]
I'll see if I can put something together... not exactly the easiest thing to do since it's a complicated production app built around Redux and using real API calls to a private network.

**Comment by kirjs** [comment]
I could ping you in hangouts and we could try debugging it together?

**Comment by joshburgess** [comment]
Sounds good to me.

**Comment by kirjs** [comment]
What's your gmail address?

**Comment by joshburgess** [comment]
joshburgess.webdev@gmail.com

**Comment by ZTjack** [comment]
I got the same problem....

**Comment by ZTjack** [comment]
I got the same problem as Josh's second one.
Just now, I added isPureConfig in my code. It's worked!!
<ReactHighStocks config={config} isPureConfig />

**Comment by ZTjack** [comment]
又遇到这个问题了，这次又理解了一次，isPureConfig简单来说，就是在shouldComponentUpdate方法里面多加了一个判断项，防止Rerender，所以，config一定来自state或者props（我用的redux）
https://github.com/kirjs/react-highcharts/blob/master/src/chartsFactory.jsx
