### ISSUE TITLE
renderer

### ISSUE THREAD

**Issue by vim-zz** [kirjs/react-highcharts#173]
is there a way accessing the highcharts renderer, equivalent to:
```
var chart = new Highcharts.Chart ... 
chart.renderer...
```
http://jsfiddle.net/phpdeveloperrahul/HW7Rm/

OR

```
renderer = new Highcharts.Renderer(
    $('#container')[0],
    400,
    300,
);
```
http://jsfiddle.net/gh/get/jquery/1.7.1/highslide-software/highcharts.com/tree/master/samples/highcharts/members/renderer-basic/

**Comment by kirjs** [comment]
feel free to reopen

**Comment by vim-zz** [comment]
thanks i will check this
