### ISSUE TITLE
Draw any shape like rectangle on selection event in chart options.

### ISSUE THREAD

**Issue by kaushikbarodiya** [kirjs/react-highcharts#174]
I am trying to achieve this http://jsfiddle.net/meFgf/. But since chart object is not available I am facing issue. Can you help me with that

**Comment by fr3dgentil** [comment]
You only need to add the config of the chart in the right place.

**1. In your jsfiddle, the config of the chart is the object here:**

`var chart = new Highcharts.Chart( {
  // THE BIG OBJECT HERE IS THE CONFIG
} )`

**2. Paste the config at the right place.**

You need to copy the code of the documentation [](https://github.com/kirjs/react-highcharts#webpackbrowserify) and put the config here:

`const config = {
  /* HighchartsConfig */
};`

That's all !

**Comment by kaushikbarodiya** [comment]
Thanks,

You mentioned correctly about placing the config in right place.I did that. But problem arises since we don't have chart object defined in selection event, so we wont be able to use it. Great help if you can attach jsFiddle for the point you are making.

**Comment by fr3dgentil** [comment]
Haha thank you, I didn't grasp the question correctly the first time.

For accessing your chart, you only have to add to reference it in _componentDidMount()_ as explain here [https://github.com/kirjs/react-highcharts#accessing-highcharts-api-after-render](https://github.com/kirjs/react-highcharts#accessing-highcharts-api-after-render)

That will give:

https://jsfiddle.net/fredgentil/6mh8a7hh/

**Comment by kaushikbarodiya** [comment]
Again, I will say you didn't grasp the question properly. :)
Problem is with accessing the chart inside the selection event not in componentDidMount. 
Specifically at this point
                 ```
 selection: function(event) {
                    var xMin = **chart**.xAxis[0].translate((event.xAxis[0]||**chart**.xAxis[0]).min),
                        xMax = **chart**.xAxis[0].translate((event.xAxis[0]||**chart**.xAxis[0]).max),
                        yMin = **chart**.yAxis[0].translate((event.yAxis[0]||**chart**.yAxis[0]).min),
                        yMax = **chart**.yAxis[0].translate((event.yAxis[0]||**chart**.yAxis[0]).max);

                    rectangle.attr({
                        x: xMin + **chart**.plotLeft,
                        y: chart.plotHeight + **chart**.plotTop - yMax,
                        width: xMax - xMin,
                        height: yMax - yMin
                    });
                    
                    return false;
                } 
```
Now, Since I want to draw the shape only on selection event.

**Comment by fr3dgentil** [comment]
I have figured it out. Because the function `selection` is only called when the chart is already created, you can access the `**chart**` with `this.refs.chart.getChart()` in `componentDidMount`. It's the same thing that is happening in the original code.

[https://jsfiddle.net/fredgentil/mem1kxtf/](https://jsfiddle.net/fredgentil/mem1kxtf/)

**Comment by kaushikbarodiya** [comment]
Thanks. I have figured out that this inside the selection event refer to
chart itself so I am taking benefit of that.

**Comment by fr3dgentil** [comment]
I'm glad to read that. Do you mean like that?

```
selection: function(event) {
    var xMin = this.xAxis[0]
```

**Comment by fr3dgentil** [comment]
Ok! Sorry for misreading btw...

**Comment by kirjs** [comment]
Thanks @kaushikbarodiya  and @fr3dgentil 
Now this is my favorite issue :)
