### ISSUE TITLE
Error using click event in plotOptions.series.events

### ISSUE THREAD

**Issue by chevin99** [kirjs/react-highcharts#175]
Using this:

```
const config = {
  xAxis: {
    categories: ['Jan', 'Feb']
  },
  plotOptions: {
    series: {
      cursor: 'pointer',
      events: {
        click: function (event) {
          console.log('yay');
        }
      }
    }
  },
  series: [{
    data: [29.9, 71.5]
  }]
}

ReactDOM.render(<ReactHighcharts config = {config}></ReactHighcharts>, document.getElementById('app'));
```

When I try to click on the series I see this error:

`highcharts.js:7 Uncaught TypeError: Cannot assign to read only property 'target' of object '#<MouseEvent>'`

But the exact same config works fine when using highcharts by itself: http://jsfiddle.net/m8r5m6m0/

**Comment by kirjs** [comment]
Hi Kevin, can you please help me reproduce it?
http://jsbin.com/lelirezine/4/edit?html,js,output

**Comment by chevin99** [comment]
I'm not sure why, but it appears that using the babel es2015 preset with webpack is somehow causing the problem.  I added a pattern to exclude highcharts from being loaded with that es2015 preset and it works ok.  Thanks for looking into it.

**Comment by dergachevm** [comment]
@chevin99 how you exclude it? Could you add example?

**Comment by chevin99** [comment]
@dergachevm, here you go:

```
loaders: [
      {
        test: /\.js?$/,
        .....        
        exclude: /high(charts|maps)\.js$/
      }
]
```

**Comment by dergachevm** [comment]
@chevin99 thank you!
