### ISSUE TITLE
Does ReactHighstock do everything ReactHighchart does? ex Pie chart?

### ISSUE THREAD

**Issue by alecperkey** [kirjs/react-highcharts#180]
Q: Can we use ReactHighstock for chart types not included in the available plotOptions listed here? http://api.highcharts.com/highstock#plotOptions 

According to http://api.highcharts.com/highstock#chart.type ...
```The default series type for the chart. Can be any of the chart types listed under plotOptions. Defaults to line.```

I have working PIE using ReactHighchart, but same config does not work as prop to ReactHighstock. I see I can have both ReactHighstock and ReactHighchard components active on same page, but I worry this is additional bloat to the codebase (because highcharts code is included in highstock afaik).

Thanks for insights!

**Comment by alecperkey** [comment]
Forgot to say, the error I get was ```cannot set property 'options' of undefined``` thrown somewhere in the Highstock code. 

Somewhere... because it is minified/obfuscated (maybe by the incomprehensible magic of my webpack setup... but probably it was minified already). Is there a way to run with underlying highchart/highstock codebase unminified for debugging? Appreciate any tips still always trying to learn. 

Great work so far & thanks much :100:

**Comment by kirjs** [comment]
My understanding is that Highstock is has a superset of abilities of Highcharts, but I'd recommend you confirm it with Highcharts people. 

This should help you if that is the case:
https://github.com/kirjs/react-highcharts#passing-highcharts-instance-manually

**Comment by kirjs** [comment]
Feel free to reopen
