### ISSUE TITLE
Tooltip configuration

### ISSUE THREAD

**Issue by pypetey** [kirjs/react-highcharts#183]
Hey
I'm trying to configure a tooltip for my data points.

I'm trying to achieve following tooltip format:
```
line 1: date - hour
line 2: weight kgs
```

example:
```
01/01/2013 - 10:03AM
75kg
```

How do I do this with react-highcharts? I tried adding formatter to tooltip but it did not affect displayed results at all.

I use following configuration file:

```
    var config = {
      rangeSelector: {
        selected: 1
      },
      chart: {
        backgroundColor: null
      },
      title: {
        text: null
      },
      series: [{
        name: 'Weight',
        data: this.state.data,
        tooltip: {
          formatter: function () {
            var result = `Example `
            return result
          },
          valueDecimals: 2,
        }
      }]
    }
```

`<ReactHighstock config={config}/>`

**Comment by kirjs** [comment]
How would you do it with a regular highcharts?

**Comment by kirjs** [comment]
Feel free to reopen
