### ISSUE TITLE
when will get react-native version？

### ISSUE THREAD

**Issue by walter211** [kirjs/react-highcharts#185]
trying to integrate on mobile

**Comment by kirjs** [comment]
This sounds very unlikely, as far as I know Highcharts is focused on DOM.
You would probably get a better answer if you ask the same question in the actual highcharts repo.  Also there is a variety of native alternatives out there.

**Comment by kirjs** [comment]
Feel free to reopen

**Comment by donaldmorton** [comment]
https://github.com/TradingPal/react-native-highcharts
