### ISSUE TITLE
How to get an SVG of a highchart

### ISSUE THREAD

**Issue by SubhuMS** [kirjs/react-highcharts#186]
Hi, i am trying to export the HighChart to the PDF with the other data from the screen. I have imported HighCharts more and HighChartsExporting as below

import Chart  from 'react-highcharts';
import HighChartsMore from 'highcharts-more';
import HighchartsExporting  from 'highcharts-exporting';

HighChartsMore(Chart.Highcharts);
HighchartsExporting(Chart.Highcharts);

Chart is been displayed in screen and i have disabled the navigation button displayed in the chart. I have a button to export the chart along with other details from screen to PDF, Now can anyone help on how to copy the chart as an image to the PDF.

**Comment by kirjs** [comment]
Look up highcharts-exports

**Comment by SubhuMS** [comment]
@kirjs, i used the highcharts-exports i dont require the download button, so i disabled it and i added the below code for converting SVG to JPG,

svg = this.refs.optionChart.getSVG();
      var width = parseInt(svg.match(/width="([0-9]+)"/)[1]),
          height = parseInt(svg.match(/height="([0-9]+)"/)[1]);
      canvas = document.createElement('canvas');
      canvas.setAttribute('width', width);
      canvas.setAttribute('height', height);
        var ctx = canvas.getContext("2d");
        img = document.createElement("img");
        img.setAttribute("src", "data:image/svg+xml;base64," + btoa(svg));  
        ctx.drawImage(this, 0, 0);
        imgsrc = canvas.toDataURL("image/png"); 
var doc = new jsPDF();
doc.addImage(imgsrc, 'PNG', 100, 60, 400, 200);

this works perefectly in chrome browser but in IE11 it doesnt work,  when i tried to use canvg then i try to use i get the below error,

Object doesn't support this action in canvg.js file (var color = new RGBColor(this.value)); so i am not sure how to convert this svg to img which works in other browser aswell

**Comment by SubhuMS** [comment]
Hi in jquery we are using below code to export chart from the program code,

**Comment by kirjs** [comment]
you should be access the chart by doing this: 
https://github.com/kirjs/react-highcharts#accessing-highcharts-api-after-render

**Comment by stevewillard** [comment]
Anyone run into an issue where getSVG is not defined? I can get access to the chart object using a ref, but for some reason I can't get to the SVG.

**Comment by stevewillard** [comment]
Turns out you need to include the `exporting` library, otherwise you won't get this method. I also needed to use the `withHighcharts` method to pass around the same instance of Highcharts. Here's how I did it:

```
import Highcharts from 'highcharts';
import exporting from 'highcharts/modules/exporting';
import RHC from 'react-highcharts';

exporting(Highcharts);
const ReactHighcharts = RHC.withHighcharts(Highcharts);
```

**Comment by kirjs** [comment]
Thanks Steve, this seems resolved?

**Comment by stevewillard** [comment]
Yup -- thanks.

**Comment by dangnelson** [comment]
I'm having the same issue, and keep getting an error that getSVG() is undefined:

    import React, { Component } from 'react';
    import RHC from 'react-highcharts';
    import Highcharts from 'highcharts';
    import HighchartsExporting from 'highcharts/modules/exporting';
    
    HighchartsExporting(Highcharts);
    const ReactHighcharts = RHC.withHighcharts(Highcharts);
    
    
    class Chart extends Component {
    
      componentDidMount() {
        console.log(this.refs[this.props.name].getSVG());
      }
    
      render() {
    
        return (
            <ReactHighcharts config={this.props.config} ref={this.props.name}/>  
        );
      }
    }
    
    export default Chart;

Error:

> TypeError: this.refs[this.props.name].getSVG is not a function. (In 'this.refs[this.props.name].getSVG()', 'this.refs[this.props.name].getSVG' is undefined)

**Comment by samimh88** [comment]
@dangnelson change your code to

`console.log(this.refs[this.props.name].getChart().getSVG());`
