### ISSUE TITLE
chart.series.addPoint is not a function

### ISSUE THREAD

**Issue by miapoulos** [kirjs/react-highcharts#19]
Cannot get many functions in Highcharts API to work. Getting errors like 'chart.series.addPoint is not a function' and 'chart.addPoint is not a function' for addPoint, setData, etc.

    var chart = this.refs.chart.getChart();
    chart.series.addPoint({
        color: "#000",
        name: "Adding A Point",
        value: "$ 1234.00",
        y: 1234.00
    });

**Comment by kirjs** [comment]
Hi Miapoulos,  what about `chart.series[0].addPoint` ?

**Comment by miapoulos** [comment]
That did it, thanks!! Was following the example... might be worth it to update it.

**Comment by kirjs** [comment]
Which example are you talking about?

**Comment by miapoulos** [comment]
In the README.md:

componentDidMount() {
    let chart = this.refs.chart.getChart();
    chart.series.addPoint({x: 10, y: 12});
  }

**Comment by kirjs** [comment]
Thanks a lot, I have updated the readme!
