### ISSUE TITLE
No way to change height besides putting hard values in the chart config

### ISSUE THREAD

**Issue by arift** [kirjs/react-highcharts#191]
Chart height always defaults to 400px regardless of what the height of the parent container is. You can only change this by changing the highchart config, which only allows pixel values. 

[http://jsbin.com/mawelunaji/edit?js,output](http://jsbin.com/mawelunaji/edit?js,output)

**Comment by arift** [comment]
Apparently that's what `domProps` is for. Closing.

**Comment by bernatfortet** [comment]
Could you explain a little bit more about your solution?
I'm having the same problem.

**Comment by arift** [comment]
I don't use this lib any more but `domProps ` property allows you to pass props to the parent div of the chart. This way you can set it's height to something more dynamic.

**Comment by bernatfortet** [comment]
Got it
