### ISSUE TITLE
Highcharts 5 is out

### ISSUE THREAD

**Issue by aldendaniels** [kirjs/react-highcharts#192]
@kirjs Just a heads-up: Highcharts 5 is out, with a new build system and built-in support for CommonJS: http://www.highcharts.com/news/236-highcharts-5-0

**Comment by amelon** [comment]
Could you please publish v10.0.2?

**Comment by piotr-szachewicz** [comment]
yes, a released version with updated Highcharts would be very useful... :)

**Comment by kirjs** [comment]
Thanks @aldendaniels and everybody, I'll figure it out over the weekend.

**Comment by kirjs** [comment]
+ react-highcharts@11.0.0
Thanks everybody
