### ISSUE TITLE
whether does it support bubble charts?

### ISSUE THREAD

**Issue by codepandy** [kirjs/react-highcharts#193]
the below is my code,but the chart can't be show.

``` jsx
const bubbleConfig = {
    chart: {
        type: 'bubble',
        plotBorderWidth: 1,
        zoomType: 'xy'
    },

    legend: {
        enabled: false
    },

    title: {
        text: 'Sugar and fat intake per country'
    },

    subtitle: {
        text: 'subtitle'
    },

    xAxis: {
        gridLineWidth: 1,
        title: {
            text: 'Daily fat intake'
        },
        labels: {
            format: '{value} gr'
        },
        plotLines: [ {
            color: 'black',
            dashStyle: 'dot',
            width: 2,
            value: 65,
            label: {
                rotation: 0,
                y: 15,
                style: {
                    fontStyle: 'italic'
                },
                text: 'Safe fat intake 65g/day'
            },
            zIndex: 3
        }]
    },

    yAxis: {
        startOnTick: false,
        endOnTick: false,
        title: {
            text: 'Daily sugar intake'
        },
        labels: {
            format: '{value} gr'
        },
        maxPadding: 0.2,
        plotLines: [ {
            color: 'black',
            dashStyle: 'dot',
            width: 2,
            value: 50,
            label: {
                align: 'right',
                style: {
                    fontStyle: 'italic'
                },
                text: 'Safe sugar intake 50g/day',
                x: -10
            },
            zIndex: 3
        }]
    },

    tooltip: {
        useHTML: true,
        headerFormat: '<table>',
        pointFormat: '<tr><th colspan="2"><h3>{point.country}</h3></th></tr>' +
        '<tr><th>Fat intake:</th><td>{point.x}g</td></tr>' +
        '<tr><th>Sugar intake:</th><td>{point.y}g</td></tr>' +
        '<tr><th>Obesity (adults):</th><td>{point.z}%</td></tr>',
        footerFormat: '</table>',
        followPointer: true
    },

    plotOptions: {
        series: {
            dataLabels: {
                enabled: true,
                format: '{point.name}'
            }
        }
    },

    series: [ {
        data: [
            { x: 95, y: 95, z: 13.8, name: 'BE', country: 'Belgium' },
            { x: 86.5, y: 102.9, z: 14.7, name: 'DE', country: 'Germany' },
            { x: 80.8, y: 91.5, z: 15.8, name: 'FI', country: 'Finland' },
            { x: 80.4, y: 102.5, z: 12, name: 'NL', country: 'Netherlands' },
            { x: 80.3, y: 86.1, z: 11.8, name: 'SE', country: 'Sweden' },
            { x: 78.4, y: 70.1, z: 16.6, name: 'ES', country: 'Spain' },
            { x: 74.2, y: 68.5, z: 14.5, name: 'FR', country: 'France' },
            { x: 73.5, y: 83.1, z: 10, name: 'NO', country: 'Norway' },
            { x: 71, y: 93.2, z: 24.7, name: 'UK', country: 'United Kingdom' },
            { x: 69.2, y: 57.6, z: 10.4, name: 'IT', country: 'Italy' },
            { x: 68.6, y: 20, z: 16, name: 'RU', country: 'Russia' },
            { x: 65.5, y: 126.4, z: 35.3, name: 'US', country: 'United States' },
            { x: 65.4, y: 50.8, z: 28.5, name: 'HU', country: 'Hungary' },
            { x: 63.4, y: 51.8, z: 15.4, name: 'PT', country: 'Portugal' },
            { x: 64, y: 82.9, z: 31.3, name: 'NZ', country: 'New Zealand' }
        ]
    }]
}

<ReactHighcharts config = {bubbleConfig}></ReactHighcharts>
```

**Comment by elmoro666** [comment]
Hi

I haven't tested your code, but to display a bubblechart, you need to add a reference to highcharts-more. So it would look something like this:

![image](https://cloud.githubusercontent.com/assets/15340253/19644855/60287592-99f2-11e6-9eeb-963d9748ade4.png)

In your package.json you will need both of these:

![image](https://cloud.githubusercontent.com/assets/15340253/19644937/9e396530-99f2-11e6-94aa-470e28e3132d.png)

Maybe there is a more elegant way, but that's how I do it.

Thomas

**Comment by kirjs** [comment]
This looks right, thanks @elmoro666

**Comment by codepandy** [comment]
the below is  the key steps.

`>npm install highcharts-more`


import HighchartsMore from 'highcharts-more';

HighchartsMore(ReactHighcharts.Highcharts);

**Comment by codepandy** [comment]
@elmoro666 
if the zAxis's value is 0,how to set the bubble isn't shown?

**Comment by codepandy** [comment]
I have solved the problem.
if the value is 0,you set it `null`,it will not be shown.

**Comment by antoine35** [comment]
Hello,

I allow myself to come back to you because I try to make a bubble chart with reactHighcharts. Everything is ok with the exception of flying over the bubbles with the mouse. They change places and as the mouse change they get back to their original place. Did you have the same problem and if yes how did you solve it?

**Comment by codepandy** [comment]
hi @antoine35 
I didn't have the problem,the below url is a my demo,share you.
[bublbe_demo](http://jsfiddle.net/jason_pandy/sxxmu0tj/),
[bubble_demo](http://jsfiddle.net/jason_pandy/0zf5dgzm/)

**Comment by antoine35** [comment]
hi @codepandy ,
Thanks for your demo but my problem was using bubble with ReactHighcharts. When I use that : 

import HighchartsExporting from 'highcharts-exporting';
HighchartsExporting(ReactHighcharts.Highcharts);
import HighchartsMore from 'highcharts-more';
HighchartsMore(ReactHighcharts.Highcharts);

I have the problem.

I solved it replacing the import of HighchartsMore like : 

import HighchartsExporting from 'highcharts-exporting';
HighchartsExporting(ReactHighcharts.Highcharts);
import HighchartsMore from 'highcharts-release/highcharts-more';
HighchartsMore(ReactHighcharts.Highcharts);

I think that the version of highcharts-more of highcharts-release is more recent than the version included in the package of ReactHighcharts

My versions : 
 "highcharts-release": "^5.0.5",
 "react-highcharts": "^12.0.0",
