### ISSUE TITLE
highstock not work

### ISSUE THREAD

**Issue by ofirk12** [kirjs/react-highcharts#194]
the main example work for my , but i want to use highstock and this is not work 
when i am write only the code :
 var ReactHighstock = require('react-highcharts/ReactHighstock.src');
i am get this error:
Cannot resolve module 'react-highcharts/ReactHighstock.src

**Comment by kirjs** [comment]
Is the the file in the actual folder?
try 'react-highcharts/dist/ReactHighstock.src

**Comment by ofirk12** [comment]
its work now but i saw now that all it compressed and the tooltip the text in outside
`<img src="http://www.interload.co.il/upload/9464211.png">`
i didnt caught the tooltip you have any idea what to do ?
