### ISSUE TITLE
plugin compressed

### ISSUE THREAD

**Issue by ofirk12** [kirjs/react-highcharts#195]
its work now but i saw now that all it compressed and the tooltip the text in outside

https://i.imgsafe.org/dcd4b0b46c.png

i didnt caught the tooltip you have any idea what to do ?

**Comment by kirjs** [comment]
Is i the same without react-highchart?

**Comment by Jakehp** [comment]
@ofirk12 provide a [JSBin](http://qs.js.org/jsbin/react-highcharts?autostart) at the very least

**Comment by kirjs** [comment]
Feel free to reopen.
