### ISSUE TITLE
Add highcharts-more

### ISSUE THREAD

**Issue by samuelmartineau** [kirjs/react-highcharts#2]
Hi Kirill, 

Is it possible to require highcharts-more (http://www.highcharts.com/component/content/article/2-articles/news/46-gauges-ranges-and-polar-charts-in-beta) to allow us to use beta features like gauge?

Thk

**Comment by kirjs** [comment]
Hi Samuel, 

I don't see why not, could be required like  `require('react-highcharts/more')` probably?

I saw you forked it, let me know if you want to collaborate.

**Comment by samuelmartineau** [comment]
Yeah it's just about including highcharts-more's script. If you look at my fork, I've just added this line
```javascript
require('exports!Highcharts/js/highcharts-more.src');
```
in ./src/Highcharts.jsx

I've just created a pull request if you want to merge it.
https://github.com/kirjs/react-highcharts/pull/3

Regards
