### ISSUE TITLE
configuration file modification many times to create highcharts instance

### ISSUE THREAD

**Issue by monsterooo** [kirjs/react-highcharts#203]
jsbin:
http://jsbin.com/rerayi/edit?js,output

in case, When I have modified the state date
```
componentDidMount() {
    const self = this;
    setTimeout(function() {
      self.setState({
        data: config2
      });
    }, 3000);
  }
```

page scrollbar will move up。

I found the reason in code:
https://github.com/kirjs/react-highcharts/blob/master/src/chartsFactory.jsx#L27
every time will create a highcharts instance。

In my project。I made some modification
```
if(this.chart) {
  this.chart.series[0].update({
    data: config.series[0].data
  });
} else {
  this.chart = new Highcharts[chartType]({
        ...config,
        chart: {
          ...chartConfig,
          renderTo: this.refs.chart
        }
      }, this.props.callback);
}
```

I don't have the ability to submit pr :(
I hope the author can fix it :)

**Comment by elmoro666** [comment]
@monsterooo  It seems to me that you are only interested in updating/changing the data series. Doing it through the config is not the correct way to do it in my opinion. Keep the config unchanged (unless you really want to change it), and only update the series. Here is an example

https://jsfiddle.net/69z2wepo/62754/

The fiddle is not necessarily the best way to structure it, it's just an example.
