### ISSUE TITLE
Can't display datetime label in xAxis

### ISSUE THREAD

**Issue by ittus** [kirjs/react-highcharts#205]
**Issue summary**:
Can't display datetime label in xAxis of react-highcharts. Instead, it shows auto incremental number.

**Reproduce**:
http://jsbin.com/vilagas/edit?html,output

![Image](https://www.dropbox.com/s/w0u7ms266m6nldp/Screen%20Shot%202016-11-23%20at%206.35.15%20PM.png?raw=1)

**Technical details**:
```
└─┬ react-highcharts@11.0.0 
  └── highcharts@5.0.4 
├── react@15.4.0
```

If I downgrade to `highcharts@4.2.5` and `react-highcharts@19.0.0 ` then it works fine.

**Comment by kirjs** [comment]
Hey Thung, thanks for the repro, are you sure this is actually specific to react-highcharts, and would work correctly if you just highcharts 5.0.4?

**Comment by ittus** [comment]
It happens with highcharts only, too
http://jsfiddle.net/LLExL/6772/

**Comment by kirjs** [comment]
Then highchairs repository would be the best place for an issue

**Comment by ittus** [comment]
Reported at https://github.com/highcharts/highcharts/issues/6026
