### ISSUE TITLE
Drilldown not working with require or import (ES6)

### ISSUE THREAD

**Issue by rasmuslundberg** [kirjs/react-highcharts#206]
Hi! 

First of all thanks for the great work on this lib, i really appreciate it! 
I have tried everything i can think of to make the drilldown work with a pie chart, but its not possible no mather how i try. Here is my code for the import section: 
```
const Highcharts = require('highcharts')
const ReactHighcharts = require('react-highcharts')
const highchartsData = require('highcharts-data')

const higchartsDrilldown = require('highcharts-drilldown')
```

then later i try to 
```
  class Chart extends Component {

  componentDidMount () {
    highchartsData(Highcharts)
    higchartsDrilldown(Highcharts)
  }

  componentWillUnmount () {
    this.chart.destroy()
  }

  render () {
    return (
      <div className='chart__chart-item'>
        <Highcharts config={this.props.config} callback={() => console.log('callback test from HChart')} />
      </div>
    )
  }
}

Chart.propTypes = {
  config: PropTypes.object.isRequired
}

export default Chart
```

The config is provided by a parent component and follows the standard structure from Highcharts website. I have a pie chart with som drilldowns. Does anyone know if this is a known bug? 

Feel a bit weird that something as simple as importing a js lib has gotten harder to do with the new syntax(s), am i missing something obvious here?

**Comment by rasmuslundberg** [comment]
update: i have also tried to follow this: (http://stackoverflow.com/questions/36942613/highcharts-drilldown-not-working-when-module-is-imported-react) example, it doesnt work either...

**Comment by kirjs** [comment]
Hey Rasmus, really sorry it gives you trouble.

Have you tried applying the lib right away?
```javascript
const Highcharts = require('highcharts');
const ReactHighcharts = require('react-highcharts');
const highchartsData = require('highcharts-data');

const higchartsDrilldown = require('highcharts-drilldown');
higchartsDrilldown(Highcharts);
```

My guess is that you're currently doing it too late.

**Comment by rasmuslundberg** [comment]
I will give that a try, thank you!

**Comment by rasmuslundberg** [comment]
Hi! 

Unforthunately it doesnt work, i've ran into another problem instead. 

When using the follwing requires: 
```
const Highcharts = require('highcharts')
const ReactHighcharts = require('react-highcharts')
const HighchartsDrilldown = require('highcharts-drilldown/drilldown.js')
HighchartsDrilldown(Highcharts)
```

To following error is received: 

```
drilldown.js:17 Uncaught ReferenceError: Highcharts is not defined
```

**Comment by rasmuslundberg** [comment]
Update: i also tried, 
```
var Highcharts = require('highcharts')
window.Highcharts = Highcharts
const ReactHighcharts = require('react-highcharts')
const HighchartsDrilldown = require('highcharts-drilldown/drilldown.js')
HighchartsDrilldown(Highcharts)
```
Then i get error: 
drilldown.js:1Uncaught ReferenceError: HighchartsAdapter is not defined(…)

This is very strange...

**Comment by kirjs** [comment]
```JavaScript
var Highcharts = require('highcharts')
const ReactHighcharts = require('react-highcharts')
console.log(Highcharts);
console.log(ReachHighcharts);
```

**Comment by rasmuslundberg** [comment]
Hi! 



Its actually working now, im using: 
var Highcharts = require('highcharts')
const ReactHighcharts = require('react-highcharts')
const HighchartsDrilldown = require('highcharts/modules/drilldown')
HighchartsDrilldown(Highcharts)

its not working with external package 'highcharts-drilldown'

**Comment by kirjs** [comment]
Thanks, make sense

**Comment by Strateus** [comment]
For those who uses ReactHighcharts:
HighchartsDrilldown(ReactHighcharts.Highcharts);
