### ISSUE TITLE
How to use highcharts-3d in  my react demo?

### ISSUE THREAD

**Issue by CocoChen917** [kirjs/react-highcharts#207]
Hi : I have some problem when I use react-highcharts:
my code :
import React from 'react';
import ReactDOM from 'react-dom';
import ReactHighcharts from 'react-highcharts';
import 'highcharts-3d';

then I use it like highcharts:
<div id="3DContainer" style={{height:'400px'}}>
         <ReactHighcharts config={this.state.config3D}  />
</div>

charts show in 2D,not 3D?what should I do?could you please give some 3D demo?thanks~

**Comment by kirjs** [comment]
Try importing it from 'highcharts/modules/higcharts-3d'

**Comment by CocoChen917** [comment]
Hi,I do as you said :
import React from 'react';
import ReactDOM from 'react-dom';
import ReactHighcharts from 'react-highcharts';
import 'highcharts/modules/higcharts-3d';

but webpack throw a new error 'Module not found' ,I open my file 'node_modules/highcharts/modules' there is no file named highcharts-3d; however path  ' node_modules/highcharts-3d'  have file,it doesn't support for exports module you published link is https://www.npmjs.com/package/highcharts-3d
I  also try  to require('highcharts-3d') ;but also no work for me.

you really do a great job here ,could you give some suggestion to me ?thanks

**Comment by FrantisekGazo** [comment]
I'm trying to make that work too.

when I use this:
```JavaScript
const React = require('react');
const Highcharts = require('highcharts');
const ReactHighcharts = require('react-highcharts');
```
the resulting chart is always 2D.

Adding 
```JavaScript
require('highcharts/highcharts-3d');
```
or
```JavaScript
require('highcharts/modules/highcharts-3d');
```
or using the real path to the `highcharts-3d.js` doesn't help.

@kirjs any suggestions?

**Comment by FrantisekGazo** [comment]
I was finally able to render 3D chart by installing:
```
npm i -S highcharts-3d
```
and using:
```JavaScript
const React = require('react');
const Highcharts = require('highcharts');
const ReactHighcharts = require('react-highcharts');
require('highcharts-3d')(ReactHighcharts.Highcharts);
```

Is this the correct way?

**Comment by kirjs** [comment]
It's correct if it works

**Comment by claradaia** [comment]
@FrantisekGazo would you mind explaining to me what exactly this last line is doing?

require('highcharts-3d')(ReactHighcharts.Highcharts);

I am using ES6 and I cannot figure out what the equivalent to this would be.

Also, this does not seem to be the best solution, because the npm package is 2 years old. It's likely to be outdated. Did you by any chance find another way to use the latest highcharts-3d?

**Comment by claradaia** [comment]
In case someone else faces the same question, I read some more and ended up with

```
import Highcharts from 'highcharts';
import ReactHighcharts from 'react-highcharts';
import highcharts3d from 'highcharts/highcharts-3d'
highcharts3d(ReactHighcharts.Highcharts);
```

Which worked.

**Comment by alexpoltava** [comment]
@claradaia Thanks! Also the first line is not necessary if you are using react-highcharts:
`import Highcharts from 'highcharts';`

**Comment by johnsonsamuel** [comment]
@claradaia 

import Highcharts from 'highcharts';
import highcharts3d from 'highcharts/highcharts-3d'
highcharts3d(Highcharts);

This worked for me too because I did not use 'react-highcharts'

**Comment by priyajainSE** [comment]
@claradaia I tries following your approach but it is not working for me. Kindly help me through it.

`import React, { Component } from 'react';

import Highcharts from 'highcharts';
import ReactHighcharts from 'react-highcharts'
import highcharts3d from 'highcharts/highcharts-3d';
highcharts3d(Highcharts);

const options = {
    chart: {
        type: 'pie',
        options3d: {
            enabled: true,
            alpha: 45,
            beta: 0
        },
        width: 350,
    },
    title: {
        text: ''
    },
    tooltip: {
        pointFormat: '{series.name}: <b>{point.percentage:.1f}%</b>'
    },
    plotOptions: {
        pie: {
            allowPointSelect: true,
            cursor: 'pointer',
            depth: 35,
            
            dataLabels: {
                enabled: true,
                format: '{point.name}'
            }
        }
    },
    series: [{
        type: 'pie',
        name: 'Browser share',
        
        data: [
            ['Firefox', 45.0],
            ['IE', 26.8],
            {
                name: 'Chrome',
                y: 12.8,
                sliced: true,
                selected: true
            },
            ['Safari', 8.5],
            ['Opera', 6.2],
            ['Others', 0.7]
        ]
    }]
};


export default class PiePendingStores extends Component {
    render() {
        return (
            <div>
                <ReactHighcharts config = {options} />
            </div>
        )
    }
}
`

**Comment by priyajainSE** [comment]
@johnsonsamuel  I used your approach too, but its not rendering 3D charts. Kindly help with it. 
![image](https://user-images.githubusercontent.com/49519895/64470501-93032300-d161-11e9-9cdd-c96fec1af8b0.png)

**Comment by priya0607jain** [comment]
After long hit and trials, following @claradaia and @johnsonsamuel , this thing finally worked for me:


import HighchartsReact from 'highcharts-react-official'
import Highcharts from 'highcharts';
import highcharts3d from 'highcharts/highcharts-3d';
highcharts3d(Highcharts);

**Comment by smackalpha** [comment]
> After long hit and trials, following @claradaia and @johnsonsamuel , the thing that finally worked for me:
> 
> import HighchartsReact from 'highcharts-react-official'
> import Highcharts from 'highcharts';
> import highcharts3d from 'highcharts/highcharts-3d';
> highcharts3d(Highcharts);

Worked like a charm...... :)
