### ISSUE TITLE
how to set classname?

### ISSUE THREAD

**Issue by codepandy** [kirjs/react-highcharts#209]
Hi,

 when I set the className,it was invalid. how to do it?

**Comment by Jakehp** [comment]
@codepandy You can set a class name on the root chart DOM element by utilizing `domProps`.

e.g.
```
<ReactHighstock config={myConfig)} domProps={{className: 'myCustomClassName'}} />

**Comment by codepandy** [comment]
@Jakehp  ok,thank you very much!

**Comment by Jakehp** [comment]
@codepandy can you close this?
