### ISSUE TITLE
How to set the theme in the website examples?

### ISSUE THREAD

**Issue by cemremengu** [kirjs/react-highcharts#210]
I am trying to apply this theme: http://www.highcharts.com/demo/line-time-series/grid-light

I checked this issue #5  but still could not figure out how to do it.

Would appreciate any help.

**Comment by cemremengu** [comment]
I used the exact config from the examples just replace the part referencing `Highcharts` with

```
stops: [
            [0, ReactHighcharts.Highcharts.getOptions().colors[0]],
           [1, ReactHighcharts.Highcharts.Color(ReactHighcharts.Highcharts.getOptions().colors[0]).setOpacity(0).get('rgba')]
```
                        ]

**Comment by kexir** [comment]
Just change Highcharts to ReactHighcharts. It works for me.
Hope this piece of code is useful.
import ReactHighcharts from 'react-highcharts';
const config = {
series: [{
                name: 'Target',
                type: 'polygon',
                data: [[153, 42], [149, 46], [149, 55], [152, 60], [159, 70], [170, 77], [180, 70],
                    [180, 60], [173, 52], [166, 45]],
                color: ReactHighcharts.Highcharts.Color(ReactHighcharts.Highcharts.getOptions().colors[0]).setOpacity(0.5).get(),
                enableMouseTracking: false

            }]
}
