### ISSUE TITLE
Support 'Style by CSS' functionality

### ISSUE THREAD

**Issue by Jakehp** [kirjs/react-highcharts#216]
@kirjs Currently in `react-highcharts` the only way to style is through the highcharts API. It would be extremely helpful to incorporate [Style by CSS](http://www.highcharts.com/docs/chart-design-and-style/style-by-css).

jsbin showing it is not supported:
http://jsbin.com/fahexih/edit?html,css,js,output

documentation on 'new' style by css functionality:
http://www.highcharts.com/docs/chart-design-and-style/style-by-css

Could be done via a prop such as `styleByCss`
```jsx
<ReactHighstock config={myConfig)} styleByCss={true} />
```

**Comment by kirjs** [comment]
I'm traveling ATM and won't be able to implement, but happy to merge a PR

**Comment by Jakehp** [comment]
@kirjs It looks the following would do it. The question is how to go about enabling/disabling this.

```react-highcharts/src/ReactHighcharts.jsx```
```jsx
module.exports = require('./chartsFactory.jsx')('Chart', require("highcharts/js/highcharts"));
```

```react-highcharts/src/Highstock.jsx```
```jsx
module.exports = require('./chartsFactory.jsx')('StockChart', require("highcharts/js/highstock"));
```

```react-highcharts/src/Highmaps.jsx```
```jsx
module.exports = require('./chartsFactory.jsx')('Map', require("highcharts/js/highmaps"));
```

**Comment by Jakehp** [comment]
Workaround:
```jsx
import highcharts from 'highcharts/js/highcharts'; // import style by css highcharts
const ReactHighstock = require('react-highcharts').withHighcharts(highcharts);
```

**Comment by eldadmoneta** [comment]
Hi, Are you planning on supporting this?

**Comment by kirjs** [comment]
I'll be back mid Jan, will take a closer look

**Comment by kirjs** [comment]
Hey @Jakehp  and @eldadmoneta, sorry for the delay. 
Looks like style-by-css is just a feature of a newer version of Highcharts?
Than it probably would be hard to conditionally enable disable without having to have 2 versions of Highcharts. 
`.WithHighcharts` seems like a correct way of doing that. 

Feel free to reopen if I'm misunderstanding the issue.
