### ISSUE TITLE
How can we format HighChart tooltip? 

### ISSUE THREAD

**Issue by akash-bst** [kirjs/react-highcharts#22]
Hi,

Can we use something like 

Highcharts.setOptions({
    lang: {
        thousandsSep: ','
    }
});

As using config 

var config = {
  /* HighchartsConfig */
};
React.render(<Highcharts config = {config}></Highcharts>, document.body);

So, Please let me know how to use setOptions in HighCharts.

**Comment by pixelwhip** [comment]
I was able to do this by accessing the `global.Highcharts` object in `componentDidMount`

```
  componentDidMount: function() {
    this.HighCharts = require('react-highcharts/bundle/highcharts');
    global.Highcharts.setOptions({
      lang: {
        thousandsSep: ','
      }
    });
  },```

**Comment by kirjs** [comment]
As an option `ReactHighcharts.Highcharts.setOptions()`.
Looks like we're going to get rid of global Highcharts at some point.
