### ISSUE TITLE
Boost.js module with highstock

### ISSUE THREAD

**Issue by arift** [kirjs/react-highcharts#227]
Anyone has an example of how to use the boost.js module with this? 
So far I tried 
`import ReactHighcharts from "react-highcharts/ReactHighstock";
require('highcharts-boost')(ReactHighcharts);` 
and 
`import ReactHighcharts from "react-highcharts/ReactHighstock";
require('highcharts-boost')(ReactHighcharts.ReactHighstock);`

but either they don't do anything or produce an error in the console about `win` not being defined. 

Thank you.

**Comment by kirjs** [comment]
What you're doing seems about right, if this is still relevant, can you try and reproduce it in jsbin, or at least be a bit more specific about win error, where is it caused?

**Comment by kirjs** [comment]
feel free to reopen.

**Comment by arift** [comment]
This was resolved a while ago. I'll put my solution in case someone else comes across it: 
```
import ReactHighcharts from "react-highcharts/ReactHighstock";
import Boost from "highcharts-boost";
Boost(ReactHighcharts.Highcharts);
```

Remember, Boost module won't actually do anything unless the number of points in a series is above a threshold (which i believe the default is 5000, but i could be wrong). Even if the sum of all the series points are above the default value, it still will not work unless individual series points are above the threshold. In order to get around this, you will have to add boostThreshold to the series setting and set it to whatever value you'd like. You'll have to do this for each series since there is no global setting.

**Comment by Sunzhuoyi** [comment]
<img width="466" alt="2018-01-10 10 55 58" src="https://user-images.githubusercontent.com/11895051/34753814-0f748cac-f5f5-11e7-8eeb-7614d8c2ca3c.png">

<img width="467" alt="2018-01-10 10 55 46" src="https://user-images.githubusercontent.com/11895051/34753813-0f3af118-f5f5-11e7-878c-d1d41e00cfaf.png">
when i  use boost in my project
`import * as ReactHighcharts from 'react-highcharts';
let Boost = require('highcharts-boost');
Boost(ReactHighcharts.Highcharts);`
when i change the chart's series ,it occurs to errors
<img width="463" alt="2018-01-10 10 53 47" src="https://user-images.githubusercontent.com/11895051/34753767-bdcd57da-f5f4-11e7-889d-133fecc5989d.png">
Do you have any solutions?
@arift @kirjs

**Comment by ilyjs** [comment]
@Sunzhuoyi Write to me here https://github.com/kirjs/react-highcharts/issues/362 .
