### ISSUE TITLE
Export highcharts doesn't add file extension to changed filename

### ISSUE THREAD

**Issue by hyalkaf** [kirjs/react-highcharts#231]
Unfortunately I don't think I can recreate this problem since I'm using electron for desktop and the web version instantly download the image.

I'm using react-hightcharts in my electron/react application. I wanted to add exporting functionality so I added export module. Now, when I download an image file of the chart, it opens a dialog (maybe because it's electron). The problem is that whenever I change the filename in that dialog, it overwrites the whole name + extension and the file gets saved without extension. I'm probably going to try the custom server route but it seems like more work just to change filename.

Not sure where should I post this problem since it's probably an electron issue. Any help is appreciated.

**Comment by kirjs** [comment]
Sounds like a mix of highcharts-export and electron. 
Good luck with it, and feel free to reopen if it turns out to be react-highcharts specific.
