### ISSUE TITLE
Issue with drilldown display 

### ISSUE THREAD

**Issue by somerrajab** [kirjs/react-highcharts#236]
Example: http://jsfiddle.net/gh/get/library/pure/highcharts/highcharts/tree/master/samples/highcharts/demo/pie-drilldown/

And used the same config in react component, and the results are:

First render:
![image](https://cloud.githubusercontent.com/assets/25740320/23164658/86ccadfe-f838-11e6-9855-435783adf200.png)

Click to drilldown:
![image](https://cloud.githubusercontent.com/assets/25740320/23164676/a56ccbb8-f838-11e6-9db2-4766ae9441ee.png)

click on back and drilldown again:

![image](https://cloud.githubusercontent.com/assets/25740320/23164691/bb5d38ae-f838-11e6-8d9b-7d46c9d154fb.png)

**Comment by kirjs** [comment]
If this is still relevant, would it be possible to create a reproducible example in jsfiddle? 
You can use this as a base: http://jsfiddle.net/api/post/library/pure/
Feel free to reopen

**Comment by somerrajab** [comment]
It is, if you use the chart data in http://jsfiddle.net/gh/get/library/pure/highcharts/highcharts/tree/master/samples/highcharts/demo/pie-drilldown/ and follow my steps, you will be able to see it. I will try to use your JSFiddle tonight :)

Thanks,

**Comment by czarnega** [comment]
@kirjs @somerrajab I am also seeing this same issue:
![screen shot 2017-03-28 at 4 48 36 pm](https://cloud.githubusercontent.com/assets/16884524/24426703/755727fc-13d6-11e7-95ca-dc1ee7df952c.png)

```js
const CONFIG = {
        chart: {
            type: 'pie',
        },
        title: null,
        tooltip: {
            headerFormat: null,
            pointFormat: '<b>{point.y:.2f}%</b>'
        },
        plotOptions: {
            series: {
                dataLabels: {
                    enabled: true,
                }
            }
        },
        series: [{
            name: 'Traits',
            animation: true,   
            allowPointSelect: true,
            colorByPoint: true,
            data: traitCategoryData,
            size: '80%',
            innerSize: '50%',
            colors: ['#ed5565', '#f8ac59', '#1ab394']
        }],
        drilldown: {
            animation: true,
            series: drilldownData
        },
        credits: {
            enabled: false
        }
    };

    return (
        <div style={{display:'flex',flexFlow:'row wrap'}}>
            <div className={style.reportCard}>
                <div className={style.cardTitle}>
                    <h5 className={style.title}>Traits <small>Snapshot</small></h5>
                </div>

                <div style={{display:'block'}} className={style.cardContent}>
                    <ReactHighcharts config={CONFIG} />
                </div>
            </div>
        </div>
    );
```

Looks like setting `drilldown: { animation: false }` fixes it.

**Comment by somerrajab** [comment]
@czarnega your suggested solution fixed the bug :) Thanks!
