### ISSUE TITLE
rendering react-highcharts with mount enzyme gives an InvalidCharacterError

### ISSUE THREAD

**Issue by hyalkaf** [kirjs/react-highcharts#237]
I have posted a question in [StackOverflow](http://stackoverflow.com/questions/42587215/rendering-react-highcharts-with-mount-enzyme-gives-an-invalidcharactererror) about this as I'm not sure where to look for help. The issue that I have happens when I try to render a component that has React High charts as a child using enzyme mount method for testing purposes. an Invalid Character Error is thrown. Here is a [repo](https://github.com/hyalkaf/react-highCharts-enzyme-issue). You will need to do `npm run test-mocha` to see the error.

Thank you.

**Comment by kirjs** [comment]
My recommendation would be to just mock out highcharts completely, would that help?

Please share your solution if you found one, feel free to reopen.

**Comment by ram4nd** [comment]
Use "render" instead of "mount" from enzyme.

**Comment by hyalkaf** [comment]
Hey there, 

Thanks for this library. I'm not familiar with how to go about mocking a library. What resources can I look into to help me do this?
