### ISSUE TITLE
Using ReactHighstock includes Highcharts AND Highstock in resulting bundle

### ISSUE THREAD

**Issue by martin-goette** [kirjs/react-highcharts#238]
If i use ReactHighstock as documented

`const ReactHighstock = require('react-highcharts/ReactHighstock')`

I end up having highcharts.js and highstock.js in the bundle, but this seems unneccessary since highstock.js fully includes highcharts.js.

Is there a way to prevent this, since it adds quite a bit to the resulting bundle size (~200kB minified).

Thank you!

**Comment by kirjs** [comment]
I'd maybe configure your bundler to pass highstock instead of highcharts, since if I understand correctly the are functionally identical?

Feel free to respond with your solution, or reopen if needed

**Comment by jeremy-colin** [comment]
Hello,

I have solved this problem using [webpack aliases](https://webpack.github.io/docs/configuration.html#resolve-alias)  in the webpack configuration


```
resolve: {
  alias: {
    'highcharts/highstock': path.resolve(__dirname, './node_modules/highcharts/highstock.js'),
    highcharts: path.resolve(__dirname, './node_modules/highcharts/highstock.js')
  },
  modules: ...
},
```

Then your API can even stay the same, ie even still using
`import Highcharts from 'react-highcharts';`

Actually as a side note, we tried to use 'react-highcharts/ReactHighstock' to display the same charts as we displayed before using directly  'react-highcharts' and we had some styling differences.
