### ISSUE TITLE
React Highcharts with Redux Example

### ISSUE THREAD

**Issue by Manuel83** [kirjs/react-highcharts#239]
Is there an example how to use React Highchart with Redux?
I like to update the chart data base on Redux Store property.

Thanks for any hint.

**Comment by kirjs** [comment]
I believe with redux it would be exactly the same, just the data would come from a different source for the wrapping component. 

If anybody wan't to PR an example, I'm happy to merge.

**Comment by SantanMaddi** [comment]
A simple redux structure using react-highcharts would look like - 

`initialStore = {
  config: {
  
  }
}

function getChartProps(state, props){
  return createSelector( (state, props) => state.config, (config) => config );
}

// return Chart Container Props
function mapStateToProps(state, props){

  // without selector
  return store['config'];

  // using selector
  return getChartProps(state, props);

}

// Chart component
Chart = (props) => (
  return <div><ReactHighcharts config = {props.config} /></div>
)

const ChartContainer = connect(mapStateToProps)(Chart)
`
