### ISSUE TITLE
Support for highcharts annotations

### ISSUE THREAD

**Issue by yoninn** [kirjs/react-highcharts#240]
Hi @kirjs, is it possible to add support for the Highcharts annotations Module?
http://www.highcharts.com/plugin-registry/single/17/Annotations

**Comment by tomerf8** [comment]
+1

**Comment by kirjs** [comment]
Nothing special has to be done to add annotation to react-highcharts, just include in it the codebase and start using (same as highcharts-more). 

See an example here: http://jsbin.com/wozewiqaha/edit?html,js,output

**Comment by jk171505** [comment]
Does it means that the standard highcharts config of annotations won't work?
http://jsfiddle.net/jk171505/rhgLyzj4/ - I tried to make it work with react module but it fails: http://jsbin.com/lacamulize/1/edit?html,js,output

**Comment by ilyjs** [comment]
All modules are in highcharts. 
Use `import Annotations from 'highcharts/modules/annotations';`
And any modules  import .... from 'highcharts/......'
Here is an example https://stackblitz.com/edit/react-zsnvbc
