### ISSUE TITLE
Scollbar feature not working

### ISSUE THREAD

**Issue by iambalajive** [kirjs/react-highcharts#284]
The scrollbar feature does not seem to work . Below is the piece of code . 
The scrollbar is enable in the xaxis and it doesnt seem to scroll . 
Please refer the highcharts implementation : **http://jsfiddle.net/gh/get/jquery/1.7.2/highcharts/highcharts/tree/master/samples/stock/yaxis/inverted-bar-scrollbar/**

```
var config = {
  title: {
    text: 'Hello, World!'
  },
  chart :{
  type:'bar'
  },
  xAxis: {
    scrollbar:{
    enabled:true
    },
    min:0,
    max:4,
    categories: ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec']
  },
  series: [{
    data: [29.9, 71.5, 106.4, 129.2, 144.0, 176.0, 135.6, 148.5, 216.4, 194.1, 95.6, 54.4]
  }]
};

```

**Comment by rhdoshi595** [comment]
Yes I'm having the same problem

**Comment by iambalajive** [comment]
you may want to check this . I found this to work . This is not a problem with react highcharts itself . Rather the way we use it . Hope this helps you
https://stackoverflow.com/questions/43437742/react-highcharts-scrollbar-feature-not-working

**Comment by Marindrew** [comment]
@iambalajive did this work for you? 

`import Highcharts from 'highcharts';
import Highstock from 'highcharts/highstock';
import ReactHighcharts from 'react-highcharts';

const Charts = ReactHighcharts.withHighcharts(Highstock);

...

function render() {
   <Charts isPureConfig={true} config={this.state.config}></Charts>
}   
`

For me it throws `Error: Highcharts error #17`
