### ISSUE TITLE
React.createClass is deprecated. Console warning shown in react dev mode.

### ISSUE THREAD

**Issue by xaxis-kenan** [kirjs/react-highcharts#286]
Can't reproduce in jsbin (they are probably using the minified production version of React, which will squelch these warnings).

Possible to reproduce with:
- **react-highcharts@11.5.0**
- **react@15.5.4**

![screen shot 2017-04-17 at 12 09 34 pm](https://cloud.githubusercontent.com/assets/20650187/25094778/c1c2b24c-2366-11e7-82d0-5d487a468237.png)

**Comment by damianobarbati** [comment]
any news on this?

**Comment by damianobarbati** [comment]
up! : )

**Comment by kirjs** [comment]
Create a pull request?

**Comment by xaxis-kenan** [comment]
Seems to be fixed? https://github.com/kirjs/react-highcharts/commit/46c80279cb4c4f2f9b9ba4083f76df09c4d543ce 

I'd vote to  close.

**Comment by kirjs** [comment]
If this is not fixex, please reopen
Thanks @xaxis-kenan !
