### ISSUE TITLE
Deprecated import from PropTypes from 'react'. Should use 'prop-types' package.

### ISSUE THREAD

**Issue by xaxis-kenan** [kirjs/react-highcharts#287]
Can't reproduce in jsbin (they are probably using the minified production version of React, which will squelch these warnings).

Possible to reproduce with:
- react-highcharts@11.5.0
- react@15.5.4

![screen shot 2017-04-17 at 1 06 34 pm](https://cloud.githubusercontent.com/assets/20650187/25096549/b916b03c-236e-11e7-80cf-d8b37bc3042a.png)

**Comment by dahlie** [comment]
It also gives deprecation warnings about usage of `React.createClass()`. These warnings are considered as errors in Jest tests and currently break our tests.

Fixing these should be quite straightforward.

**Comment by mtrabelsi** [comment]
I don't think that's gonna be fixed soon, the repo is not actively maintained..

**Comment by kirjs** [comment]
Going to have some time end of May, meanwhile contributors PRs welcome.

**Comment by xaxis-kenan** [comment]
Appears to be fixed here: https://github.com/kirjs/react-highcharts/commit/46c80279cb4c4f2f9b9ba4083f76df09c4d543ce
Voting to close.

**Comment by kirjs** [comment]
Ah, didn't realized upgrading fixed that too. Thanks @xaxis-kenan!
