### ISSUE TITLE
Highcharts use of React.createClass

### ISSUE THREAD

**Issue by kcharcast** [kirjs/react-highcharts#302]
`Warning: HighchartsChart: React.createClass is deprecated and will be removed in version 16. Use plain JavaScript classes instead. If you're not yet ready to migrate, create-react-class is available on npm as a drop-in replacement.`

What will happen when React drop this functionality?

**Comment by davidnoah** [comment]
I'm having this warning also, could it be one of the dependencies?

**Comment by ilyjs** [comment]
The bug is fixed!
