### ISSUE TITLE
Crosshair event click

### ISSUE THREAD

**Issue by antoine35** [kirjs/react-highcharts#306]
Hi !

Crosshair on xAxis is ok but i want to have an onclick event on.  But it does not work. Does anyone have a solution?
Thk!!

My code which doesn't work !!

xAxis : {
..... 
crosshair: true, // OK
 clickOnCrosshair: function (e) { //KO
      		console.log("crosshair click ");
 }
}

**Comment by bfang711** [comment]
Have you found the solution for this? I need a on click for corsshair as well.  thank you.

**Comment by antoine35** [comment]
Hi,

Yes, it works. You have to define the event on a serie if you want just on the serie and on the global object if you want on the crosshair.

My code example :

```
chart: {
      type: 'line',
       events : {
             click: function (e) {
	         alert("click on crosshair");
            }
        }
},
xAxis = {
      ....,
      crosshair: true,
},
series: {     
      .......,			
      point: {
                events: {
                       click: function (e) { 
			  alert("click on serie");
		        }
		}
      }
}
```

I hope it will be usefull.

**Comment by bfang711** [comment]
awesome. This works!  Thank you so much.  :+1: 

In the meantime, do you know how to get rid of this default tooltip that will follow my mouse. It is so annoying. 
![image](https://user-images.githubusercontent.com/13139744/35741259-593ec45c-0805-11e8-82b6-b58fdd017acb.png)
