### ISSUE TITLE
Explore better ways to allow highcharts to render on node

### ISSUE THREAD

**Issue by kirjs** [kirjs/react-highcharts#31]

**Comment by kirjs** [comment]
Current solution pollutes the global namespace

**Comment by aldendaniels** [comment]
An idea:

During the build process, use WebPack to generate `dist/HighchartsNode.js`, which would shim only its local scope with JSDOM. This could be done by pre-pending the following code (untested) to Highcharts:

```javascript
var document = require('jsdom').jsdom('<!doctype html><html><body><div id="test"></div></body></html>');
var window = document.defaultView;
// ... Rest of Highcarts.js here
```

Note that `require('jsdom')` should be processed by node at runtime. You'd need to keep webpack from trying to bundle JSDOM.

**Comment by kirjs** [comment]
I think the best solution would be to just mock 'Highcharts` when on node. 

Just something which has a chart function which returns an empty div. 

Unless jsdom learns how to render SVG it can't help us here.

**Comment by kirjs** [comment]
https://github.com/kirjs/react-highcharts/blob/master/recipes.md#rendering-react-highcharts-on-node
Not sure we can go better than this, let's reopen when some new way pops up.
