### ISSUE TITLE
Custom Events - React Highcharts?

### ISSUE THREAD

**Issue by brysonli12** [kirjs/react-highcharts#314]
@kirjs or someone else, I have two questions...

**Question 1**
For the regular highcharts (https://github.com/highcharts/highcharts) we have custom events (https://github.com/blacklabel/custom_events)

Is there an equivalent custom events module in react-highcharts or somewhere else or is it still to be implemented in the future?

Is there a way that I could use the functionality of custom_events with react-highcharts?

**Question 2**
What I am asking is, is it possible to make the x axis labels clickable, as shown in normal highcharts here: https://stackoverflow.com/questions/42062016/in-high-chart-how-to-add-event-for-label-click or https://stackoverflow.com/questions/45425623/highchart-add-onclick-event-for-total-value-stacklabel ?

Please help answer these questions if possible, or direct me to someone who can answer these questions.  Thanks!

**Comment by brysonli12** [comment]
used a different way of solving the problem (not customevents)

**Comment by cezarderevlean** [comment]
Let us know the solution...

**Comment by surmistry** [comment]
@brysonli12 did you find a third-party event handler or a different solution altogether?

**Comment by brysonli12** [comment]
what I remember is that I did it manually by calculating where the labels where and then executing an appropriate function based on it (I calculated whether or not the user clicked on the label based on where they clicked)

another one of the members on my team adapted this code from the SO link I posted..I don't have access to that code anymore, but I know he used code similar to this (he had to change it slightly though...)
chart.xAxis[0].labelGroup.element.childNodes.forEach(function(label)
{
    label.style.cursor = "pointer";
    label.onclick = function(){
      alert('You clicked on '+this.textContent);
    }
});
