### ISSUE TITLE
can't use chart.showLoading？

### ISSUE THREAD

**Issue by CherryCHan** [kirjs/react-highcharts#316]
Before Submitting an issue please reproduce it in JSBin using this setup: 
http://qs.js.org/jsbin/react-highcharts?autostart
`this.refs.chart.chart.showLoading('Loading...');`
`<HighChart config={chartConfig.config} ref="chart"></HighChart>`

**Comment by ilyjs** [comment]
You need         `this.refs.chart.getChart().showLoading('Loading...');`

> https://github.com/kirjs/react-highcharts#accessing-highcharts-api-after-render
