### ISSUE TITLE
Feature request -- add export module

### ISSUE THREAD

**Issue by jasongonzales23** [kirjs/react-highcharts#32]
Thanks for this module! It's made my job so quick and easy. I know that my PM will want exporting soon, so I am thinking adding the exporting module (found here: http://code.highcharts.com/) will be a nice addition.

I intend to just try to add it here myself and then file a PR, but if someone beats me to it, I will send you a beer!

**Comment by jasongonzales23** [comment]
alternatively it might make sense to just wrap the native code so it can be imported via CommonJS.  Or both? Thoughts?

**Comment by kirjs** [comment]
I've never used the export module before but to my understanding there in no React needed to use it. 

So commonJS wrapper would be the right solution. Maybe an issue to highcharts release would make sense to see if they are up to making modules commonJS compatible.

**Comment by kirjs** [comment]
Starting with v3 you should be able to do `require('react-highcharts/modules/exporting')`, that should fix the issue

**Comment by jasongonzales23** [comment]
That's awesome thanks @kirjs !!! So grateful for all you banged out this week :beers:
