### ISSUE TITLE
Treemap support 

### ISSUE THREAD

**Issue by CallMeXYZ** [kirjs/react-highcharts#321]
it seems that we cannot using ` treemap`  directly and theere was only highmap``

**Comment by ram-g-athreya** [comment]
Hi @CallMeXYZ 

I am facing the same issue how exactly did you create a treemap? I am getting an error saying that the series is invalid.

Thanks
Ram

**Comment by bernatfortet** [comment]
Same here

**Comment by itsnauman** [comment]
I'm getting this issue too

**Comment by jarodchampsmith** [comment]
I'm getting this issue too
