### ISSUE TITLE
drilldown bug

### ISSUE THREAD

**Issue by scheiblr** [kirjs/react-highcharts#323]
First of all thanks a lot for this react lib.
Unfortunately, I encountered a bug, which didn't let me implement the drilldown chart like here:
http://jsfiddle.net/6LXVQ/97/

Here the code of the bug:
https://github.com/schmittr/react-highcharts-drilldown

Would be nice to have this fixed soon. Maybe it's an issue of the highcharts version used by react-highcharts?

Kind regards,
Raphael

EDIT: I just found out, that when I move the window the diagram is in, such that it's kinda redrawn, the colors adjust.. weird thing. Still one Element is keeping there though..

**Comment by scheiblr** [comment]
Solution found: the npm drilldown package is old. Would it be possible for you to update these plugins? that would be very kind and nice!

**Comment by mohannadsalem** [comment]
@scheiblr as for the expanding of the pie chart on click on one of the labels just define a size key in the both of the series.

**Comment by scheiblr** [comment]
Thanks. A much cleaner solution to me was to download and import the drilldown extension manually (not by the npm package).
