### ISSUE TITLE
Support for React 16

### ISSUE THREAD

**Issue by wojtekmaj** [kirjs/react-highcharts#324]
Hey there,
are you planning to officially support React 16?
I have tested this library with 16.0.0-rc.2 and so far, so good.

I'd appreciate feedback from other users how well react-highcharts behaves on their React 16-based environments.

If the feedback will be positive, updated react-highcharts stating React 16 compatibility would be great.

**Comment by will-stone** [comment]
I'm getting this in RC3 / 12.0.0

```
Warning: Setting defaultProps as an instance property on HighchartsChart is not supported and will be ignored. Instead, define defaultProps as a static property on HighchartsChart.
```

From what I can tell, I'm not passing anything weird in to the react-highcharts plugin.

**Comment by jibees** [comment]
I suppose the solution is to add static before defaultProps in this file:
https://github.com/kirjs/react-highcharts/blob/master/src/chartsFactory.jsx

**Comment by alexpoltava** [comment]
Still have this warning with React 16.0.0 release version.

**Comment by hossein-** [comment]
Any update on this?

**Comment by alexpoltava** [comment]
Lets wait for
https://github.com/kirjs/react-highcharts/issues/333

**Comment by ikzjfr0** [comment]
any update on this?

**Comment by wojtekmaj** [comment]
I have a bad feeling that this package is abandoned and we would need to contact npm to further work on this package.

**Comment by petertenhoor** [comment]
Any update on this? The package works fine but I also get the warning after updating to React 16.

**Comment by GuyGolanBB** [comment]
There is a PR opened with a fix but still not merged.
