### ISSUE TITLE
Cannot run the demo

### ISSUE THREAD

**Issue by Kanagamanikandan** [kirjs/react-highcharts#332]
I am getting an issue, when I tried to run the demo using the command 'npm run demo', coulf you please help me to resolve it?

[npm-debug.log](https://github.com/kirjs/react-highcharts/files/1358057/npm-debug.log)

Thanks,
Mani

**Comment by ilyjs** [comment]
Did you find a solution?

**Comment by Kanagamanikandan** [comment]
No, I was not able to resolve, anyway I don't need it now but thanks for asking.

**Comment by kirjs** [comment]
At this moment it's not possible to run the demo on windows machine, work on the solution is in progress.
