### ISSUE TITLE
Update to Highcharts 6

### ISSUE THREAD

**Issue by PhilipGarnero** [kirjs/react-highcharts#333]
[Blog post](https://www.highcharts.com/blog/news/announcing-highcharts-6/) about the new version.

**Comment by pinkynrg** [comment]
Why did you close the issue? The issue was talking about Highcharts 6, not React 16...

**Comment by swrobel** [comment]
FYI, I just updated my app to use React 16 & Highcharts 6 with react-highcharts 13.0.0 and all is working correctly for me.
