### ISSUE TITLE
How to use "Highcharts.setOptions"?

### ISSUE THREAD

**Issue by codler** [kirjs/react-highcharts#334]
I cant see "Highcharts.setOptions" in the global scope. Im using webpack, es6 and react-highcharts 12.0.0.
How can I setOptions?

**Comment by codler** [comment]
Nvm, I figured out.
```es6
import Highcharts from 'react-highcharts';
Highcharts.Highcharts.setOptions({
  lang: {
    shortMonths,
  },
});
```

**Comment by kushalmahajan** [comment]
Should be documented

**Comment by afsanefda** [comment]
> Nvm, I figured out.
> 
> ```js
> import Highcharts from 'react-highcharts';
> Highcharts.Highcharts.setOptions({
>   lang: {
>     shortMonths,
>   },
> });
> ```

It's not working for me !
