### ISSUE TITLE
Highcharts error #16

### ISSUE THREAD

**Issue by zdolozhevskiy** [kirjs/react-highcharts#344]
Hey, i have an issue: Highcharts error 16: www.highcharts.com/errors/16

Stacktrace: 
    at Object.error (highcharts.js:117)
    at highcharts.js:8
    at highcharts.js:9
    at a (highcharts.js:8)
    at Object.<anonymous> (highcharts.js:8)
    at __webpack_require__ (bootstrap 434aa3002a5ed987a726:49)
    at webpackUniversalModuleDefinition (ReactHighcharts.js:3)
    at Object.<anonymous> (ReactHighcharts.js:10)
    at __webpack_require__ (bootstrap 434aa3002a5ed987a726:49)
    at Object.<anonymous> (main.js?70c41a83f7259d04b46ec8ceb27fd652875c3c04:52662)

in my component with chart i simple require 
`import ReactHighcharts from 'react-highcharts';`
and my render method
`return <ReactHighcharts config = {this.config} />;`

I can reproduce the error when i came to my application (it renders in separate view) from view that add Highcharts to the global scope (when it can be reached via window.Highcharts) I can't change this behavior.

Is it possible for your library to use existing Highcharts from window if it exists and in case if it is not then load Highcharts from node_mobule vie require?

**Comment by alankyshum** [comment]
@zdolozhevskiy Although this happened quite a long time ago, it would be great to know how you solved this issue, coz I have recently encountered exactly the same issue.

More background about this:
1. I used Highcharts in my existing app, which is declared in `window`
2. In the `webpack.config.js` of`react-highcharts`, I see highcharts being declared, meaning that it will use window.Highcharts if possible?
https://github.com/kirjs/react-highcharts/blob/master/webpack.config.js#L45-L50

**Comment by fancymo** [comment]
I want to know how to resolve ? I met this problem.

**Comment by suhomozgy-andrey** [comment]
@alankyshum hi, I met the same problem in my app. Did you resolve yours?

**Comment by alankyshum** [comment]
@suhomozgy-andrey , yah, I managed to resolve the issue by doing the following steps.
- Turns out I don't need this package. I can simply use the original highcharts package to render charts.
- TL;DR; https://webpack.js.org/configuration/externals/, to specify Highcharts as external dependency, then use the original Highcharts API to render chart

## Webpack configurations
- 
```javascripts
{
  entry: {}, // dummy
  output: {}, // dummy
  externals: [
    { highcharts: 'Highcharts' }
  ]
}
```

## Inside the components
> Using the original Highcharts API, which looks for the ID of the chart container, and render inside that container in `componentDidMount` and `componentDidUpdate` cycle
```javascript
import * as Highcharts from 'highcharts';

export default class Chart extends React.Component<FooProps> {
  componentDidMount() {
    this.chartObj = new Highcharts.Chart(this.props.containerID, this.state.chartOptions);
  }

  componentDidUpdate() {
    this.chartObj = new Highcharts.Chart(this.props.containerID, this.state.chartOptions);
  }

  render() {
    return <div id={this.props.containerID} />;
  }
}
```
