### ISSUE TITLE
Version 15.0.0 published?

### ISSUE THREAD

**Issue by nhpace** [kirjs/react-highcharts#347]
Has v15.0.0 been published to npm yet?

**Comment by Skaronator** [comment]
Yes since about 2 hours. What has changed since v13? Changelog is outdated AF https://github.com/kirjs/react-highcharts/blob/master/CHANGELOG.md

**Comment by Tsvetkovv** [comment]
What about v.14 as well?
`npm show react-highcharts` says that the one has not been published
```
'12.0.0': '2017-04-27T04:49:39.012Z',
'13.0.0': '2017-10-11T15:26:38.119Z',
'15.0.0': '2017-11-16T19:26:08.166Z'
```

**Comment by eliseumds** [comment]
An even newer one would be great to get rid of the warnings related to "getDefaultProps()" on React 16.
