### ISSUE TITLE
Consequences of upgrading high charts?

### ISSUE THREAD

**Issue by moimikey** [kirjs/react-highcharts#35]
At the moment, `react-highcharts` depends on highcharts 2.x, and 4.x has been out now with a lot of improvements and changes. I'd guess there's work to be done for migrating, but I wanted to know if this was going to be prioritized at all.

**Comment by kirjs** [comment]
Hi Michael, 

We are using the latest version of highcharts (4.1.8). I assume the reach-highcharts version is the one which caused confusion. 

If so I'll leave the task open, and will think about the best way to keep those numbers more in sync, or to find a better way to indicate the version of Highcharts we're using.

**Comment by moimikey** [comment]
@kirjs you know what, i noticed that it was pushed to npm 3 days ago, and 3 days ago was when i saw it at 2.x still (unless i'm going crazy)

much thanks for the response!

**Comment by kirjs** [comment]
No worries!
