### ISSUE TITLE
react-hightcharts breaks

### ISSUE THREAD

**Issue by nir-welldone** [kirjs/react-highcharts#351]
After updating v15.0 the chart breaks.
Can you please update the changelog of v15.0?

Thanks

**Comment by reiff12** [comment]
Can you give an example of whats happening? I believe I'm having the same issue.

**Comment by nir-welldone** [comment]
I'm not sure.. some charts disappeared (I think when there is no data.. ?)

**Comment by reiff12** [comment]
I would verify this by either logging chart config in the console or use React Dev Tools to view props and state of the react components where your chart is.
