### ISSUE TITLE
cannot find react-highcharts v14.0.0

### ISSUE THREAD

**Issue by buzhou** [kirjs/react-highcharts#354]
get a little confused, because the recommended version is v14.0.0
<img width="262" alt="2017-12-07 14 10 22" src="https://user-images.githubusercontent.com/31878054/33701188-9e14da50-db58-11e7-9008-0f0e7f1d4f90.png">
<img width="607" alt="2017-12-07 14 10 36" src="https://user-images.githubusercontent.com/31878054/33701189-9e433558-db58-11e7-8cb5-6aedc3b48fc2.png">

**Comment by kirjs** [comment]
Ah, I accidentally bumped the version twice. 13.0.0 is the version to use.
