### ISSUE TITLE
Window to Scroll Top with react-tabs

### ISSUE THREAD

**Issue by Piero87** [kirjs/react-highcharts#358]
Hi,
I am using react-highcharts with react-tabs, and when i click a tab that contain an highchart the window scroll to top, any idea?

**Comment by ilyjs** [comment]
Show an example code. And attach dependencies.

**Comment by ilyjs** [comment]
> The solution to this problem is add minHeight 

 ```
   <TabPanel>
      <div style={{ minHeight: 800 }}>
        <ReactHighcharts  config={config}  ref="chart" > </ReactHighcharts>
      </div>
    </TabPanel>

    <TabPanel>
      <div style={{ minHeight: 800 }}>
        <ReactHighcharts  config={config}  ref="chart" > </ReactHighcharts>
      </div>
    </TabPanel>
```

> This is an example with this problem
https://stackblitz.com/edit/react-highcharts-react-tabs-scroll-problem?file=TabsExample.js

> This is a corrected example
https://stackblitz.com/edit/fix-react-highcharts-react-tabs-scroll-problem?file=TabsExample.js
