### ISSUE TITLE
Install with npm causes error

### ISSUE THREAD

**Issue by fr101ed** [kirjs/react-highcharts#36]
Hi, I use npm to install react-highcharts with react@0.14.0-rc1. And the error says:

    npm ERR! peerinvalid The package react does not satisfy its siblings' peerDependencies requirements!
    npm ERR! peerinvalid Peer react-highcharts@2.1.0 wants react@*

So how can I use react-highcharts with react@0.14.0-rc1？

**Comment by kirjs** [comment]
It seems to work fine for me.
What's in your package.json?

```bash
$ npm init -y
$ npm i -d react@0.14.0-rc1 
$ npm i -d react-highcharts
...
react-highcharts@2.1.0 node_modules/react-highcharts
npm info ok 
```

**Comment by fr101ed** [comment]
I tried what you said. But in fact, it did not act correctly. 

    $ npm init -y
    $ npm i -d react@0.14.0-rc1
    ...
    npm info ok

Until now, there is no problem. But,

    $ npm i -d react-highcharts
    ...
    npm info install react-highcharts@2.1.0
    npm info postinstall react-highcharts@2.1.0
    npm info attempt registry request try #1 at 10:24:51
    npm http request GET https://registry.npmjs.org/react
    npm http 304 https://registry.npmjs.org/react
    npm info install react@0.13.3 into /Users/fred/Work/Projects/testnpm
    npm info installOne react@0.13.3
    npm info preuninstall react@0.14.0-rc1
    npm info uninstall react@0.14.0-rc1
    npm info postuninstall react@0.14.0-rc1
    npm info preinstall react@0.13.3
    ...
    npm info ok

It seems that react-highcharts uninstall react@0.14.0-rc1 and install react@0.13.3. This is not what we want, right?

And if you try this script below, it will throw error directly.

    npm install react@0.14.0-rc1 --save
    npm install react-highcharts --save
    ...
    npm ERR! peerinvalid The package react does not satisfy its siblings' peerDependencies requirements!
    npm ERR! peerinvalid Peer react-highcharts@2.1.0 wants react@*

**Comment by kirjs** [comment]
I was able to reproduce it, seems like semver doesn't handle the `rc` part correctly. 

I'll try to look at it over the weekend, but I'm open to suggestions on how that could be fixed.

**Comment by kirjs** [comment]
rc is not a thing anymore, and react@0.14 is supported. closing the issue
