### ISSUE TITLE
Use Normal Highchart and Heatmap

### ISSUE THREAD

**Issue by Piero87** [kirjs/react-highcharts#370]
Hi,
What I have to import to use simple bar chart and a Heatmap chart in the same react component?

**Comment by ilyjs** [comment]
Hi @Piero87 !
hope this helps you
https://stackblitz.com/edit/react-pjwrhu?file=Hello.js
and 
You may need
```
import heatmap from 'highcharts/modules/heatmap';
heatmap(ReactHighmaps.Highcharts);

```
