### ISSUE TITLE
Display the area below a series for a defined range

### ISSUE THREAD

**Issue by surmistry** [kirjs/react-highcharts#375]
Hi there, I'm looking for a feature and I'm not sure if it exists. Which is a 
`series{
 fillOpacity: 0.75
}` for the area below a series plot **for a specified range,** and then multiple ranges. I tinkered with `type: area` as well as this [example](http://jsfiddle.net/gh/get/library/pure/highcharts/highcharts/tree/master/samples/highcharts/xaxis/plotbands-color/) but I can't think of a solution.
The teal area for example: 

![highchart_feature](https://user-images.githubusercontent.com/4741146/35650675-eee99416-06aa-11e8-99fd-9427aca2ab3f.jpg)

Thanks for the help in advance!

**Comment by ilyjs** [comment]
I dont know.
I recommend asking [here]( https://github.com/highcharts/highcharts/issues) and [here](https://stackoverflow.com/)
