### ISSUE TITLE
Can I make a Custom Chart?

### ISSUE THREAD

**Issue by surmistry** [kirjs/react-highcharts#378]
I'm trying to implement 
https://rawgit.com/paulo-raca/highcharts-contour/master/highcharts-contour.js 
and it just seems like it's extending Heatmaps by pulling other chart types together and I wanted to know if react-highcharts accommodates enough for me to just pull the script apart and connect it to react-highcharts?

**Comment by ilyjs** [comment]
Hi @surmistry !
 You gave too little information for this case. 
This repo https://github.com/paulo-raca/highcharts-contour 
highcharts-contour.js use https://github.com/ironwallaby/delaunay/blob/master/delaunay.js

I made an example based on https://jsfiddle.net/naq8uwLL/ 

https://stackblitz.com/edit/react-qx2nmm?file=Hello.js

**Comment by surmistry** [comment]
Thanks for the help!
