### ISSUE TITLE
heatmap support?

### ISSUE THREAD

**Issue by mblakele** [kirjs/react-highcharts#38]
Thanks for releasing react-highcharts. According to http://www.highcharts.com/docs/chart-and-series-types/heatmap a heatmap requires `modules/heatmap.js` from the highcharts distribution. Sample code http://jsfiddle.net/gh/get/jquery/1.9.1/highslide-software/highcharts.com/tree/master/samples/highcharts/demo/heatmap/

Is it possible to make this work with react-highcharts?

**Comment by kirjs** [comment]
Did you try just including the file after including Highcharts?

**Comment by mblakele** [comment]
Sorry, I should have been clearer. What I had in mind was something like `require('react-highcharts/heatmap')`, with the heatmap code included in the react-highcharts install.

**Comment by kirjs** [comment]
I see, it comes with Highcharts-common which are dependency of react-highcharts. 

I guess we could benefit of some shortcuts though.

**Comment by kirjs** [comment]
starting with v3 you should be able to `require('react-highcharts/modules/heatmap')`.

**Comment by iamricky** [comment]
I'm getting `Module not found: Error: Cannot resolve module 'react-highcharts/modules/heatmap'` whenever I require the heatmap module.

**Comment by justinlevinson** [comment]
For others having trouble, the issue may be that Heatmap is actually part of Highmaps, not Highcharts.

This works for me (stateless functional component, adapt as necessary if you have a class):

```const Highcharts = require("highcharts")
const ReactHighcharts = require("react-highcharts")
const ReactHighmaps = require('react-highcharts/ReactHighmaps.src');

const chartConfig = {
    chart: {
      type: 'heatmap',
      ...
  }
}

...

return(
  <ReactHighmaps config={chartConfig} />
)

```
