### ISSUE TITLE
Donotcharts disappearing 

### ISSUE THREAD

**Issue by pinturic** [kirjs/react-highcharts#384]
I have many donuts charts on screen.
From time to time one of them disappears and is replaced by an empty div; I am sure the config that is passed to every donut charts is correct and does not change depending on the react-redux actions that are raised.

**Comment by ilyjs** [comment]
Hi @pinturic  Make an example here  https://stackblitz.com/

**Comment by pinturic** [comment]
https://github.com/kirjs/react-highcharts/pull/388
