### ISSUE TITLE
"Accessing Highcharts API after render"

### ISSUE THREAD

**Issue by srklonaris** [kirjs/react-highcharts#385]
In the readme it says you can access the highcharts api after render?  Can I not access it before render?

I'm trying to override `Highcharts.Navigator.prototype.drawHandle` but `Highcharts` is undefined everywhere (in my constructor and in render).

I am importing ReactHighstock like:
`import ReactHighstock from 'react-highcharts/ReactHighstock';`

Even `ReactHighstock` is undefined unless I am drawing the component.

**Comment by kirjs** [comment]
https://github.com/kirjs/react-highcharts#accessing-highcharts-api-after-render
