### ISSUE TITLE
Uncaught TypeError: a.Highcharts.error is not a function

### ISSUE THREAD

**Issue by Ashwin117** [kirjs/react-highcharts#386]
I'm doing `npm install highcharts` and simply requiring...yet getting this problem at runtime.

I'm using React 16 w Webpack 3. What am i missing?

**Comment by ilyjs** [comment]
Hi @Ashwin117 I think you need to ask here. https://github.com/highcharts/highcharts/issues

**Comment by Ashwin117** [comment]
@ilyjs Hey, don't worry about it. We found the issue. It looks like the app was using an older version of highcharts already without my knowledge. This was causing conflicts. Thanks for the quick reply though.
