### ISSUE TITLE
[BUG] Highcharts already defined in the page

### ISSUE THREAD

**Issue by joshhornby** [kirjs/react-highcharts#39]
I am trying to use both `react-highcharts/more` & `react-highcharts/highstock` on the same page, this causes the following error message:

http://www.highcharts.com/errors/16

This maybe similar to this issue, https://github.com/kirjs/react-highcharts/issues/9 although I thought this had been fixed? 

I am using webpack to bundle my code.

**Comment by kirjs** [comment]
Can you try requiring `react-highcharts/node_modules/highstock-release/highcharts-more.js` instead and let me know if that fixes the issue?

**Comment by joshhornby** [comment]
`Module not found: Error: Cannot resolve module 'react-highcharts/node_modules/highstock-release/highcharts-more'`

Seems there is no `node_modules` inside the `react-highcharts` folder

**Comment by kirjs** [comment]
how about using highcharts-release instead?
Is there a node_modules folder there?

**Comment by joshhornby** [comment]
Again thats not there as its included in the `devDependencies`

https://github.com/kirjs/react-highcharts/blob/master/package.json#L28

**Comment by kirjs** [comment]
I'm closing the issue, feel free to reopen it if if you need further help
More.js does not contain highcharts anymore, but instead should be required as an add-on, that should fix the issue.
