### ISSUE TITLE
How to apply Highchart themes in ReactHighstock?

### ISSUE THREAD

**Issue by ajeshb** [kirjs/react-highcharts#391]
I need to add dark blue theme of Highcharts in ReactHighstock. I did not find any documentation of the same. Can you help me? @kirjs

**Comment by ilyjs** [comment]
Hi @ajeshb !
You need ```import NameTheme from 'highcharts/themes/name-theme';```
and ```NameTheme(ReactHighcharts.Highcharts);```

https://stackblitz.com/edit/highcharts-87w46s?file=Highchart.js

**Comment by ajeshb** [comment]
It worked @ilyjs. 
Thanks
