### ISSUE TITLE
How to update data by datetime without rerender highcharts (start time and end time set by state)

### ISSUE THREAD

**Issue by linhmanh92** [kirjs/react-highcharts#393]
<img width="1168" alt="screen shot 2018-03-12 at 4 45 29 pm" src="https://user-images.githubusercontent.com/18113639/37276722-2b2cefc0-2615-11e8-9ae1-1fc1e935a99d.png">
When i changed date time set by state then highchart render two times (when setState and get data). Can i update data by datetime without render highcharts two times (only one) with any options on react-highcharts?

**Comment by ilyjs** [comment]
Hi @linhmanh92 !
Use update. https://stackblitz.com/edit/react-x7povq?file=Hello.js

**Comment by linhmanh92** [comment]
@ilyjs can i use neverReflow bro?
