### ISSUE TITLE
I need to implement a Flag feature when two line graphs intersect

### ISSUE THREAD

**Issue by Andriy-Kulak** [kirjs/react-highcharts#396]
Hi Team!

I am need to implement a feature where there is a flag pointing out the breakeven point between two lines on a graph.

I am attempting to implement partly whats in this example (https://www.highcharts.com/demo/combo-timeline)

The options examples says `// Add flags for important milestones. This requires Highstock.` Can some please provide brief example of how this looks?

I attemping to import highstock but I am getting a very ambigous error
```
import Highcharts from 'highcharts/highstock'
import ReactHighcharts from 'react-highcharts'
```

if I use `import ReactHighstock from 'react-highcharts/ReactHighstock'` then  my line graph turns into a stock chart which is not what I want. Any ideas would be greatly appreciated

Below is the error I am getting:
```
Error: Highcharts error #17: www.highcharts.com/errors/17
```

**Comment by ilyjs** [comment]
Hi @Andriy-Kulak !
Look at the example: https://stackblitz.com/edit/react-hn3tfg?file=Hello.js

**Comment by Andriy-Kulak** [comment]
HI @ilyjs ! Thanks for the example, it is really helpful!
