### ISSUE TITLE
Use Official Highcharts NPM Package

### ISSUE THREAD

**Issue by aldendaniels** [kirjs/react-highcharts#4]
Looks like HighSlide Software is adding Highcharts to NPM: https://github.com/highslide-software/highcharts.com/issues/3616

The package is [here](https://www.npmjs.com/package/highcharts-release), but appears to still have some issues. Once resolved, it would be great if react-highcharts could use the official package instead of bundling Highcharts.

I'd suggest making Highcharts a peer dependency.

**Comment by kirjs** [comment]
+1 

Let me know if you want to follow up on that and do a pull request, otherwise I'll do it in the one of the upcoming weekends.

**Comment by aldendaniels** [comment]
@kirjs - I'm unlikely to find the time to make a PR, but I'll let you know if that changes.

As I mentioned, the NPM release isn't ready for prime-time yet. Hopefully they'll fix it quickly, but we'll see.

**Comment by kirjs** [comment]
I'm actually using browserify, which could probably make it work with AMD too, will take a look if I'll have some time this weekend

**Comment by kirjs** [comment]
Resolved by #20
