### ISSUE TITLE
How to prevent redraw when parent state change during click event

### ISSUE THREAD

**Issue by mahtikebab** [kirjs/react-highcharts#42]
Hi,
I use click events on a chart to signal my parent component what point was clicked. This in turn updates the parent's state which get sent over to the highcharts component. This causes always a redraw of the graph lines, which is something I don't want. How could I control when to redraw and when not? I tried checking if the value-table from the paren'ts state changes or not, but still the chart redraws itself no matter what.

**Comment by kirjs** [comment]
Would that help?
https://github.com/kirjs/react-highcharts#limiting-highchart-rerenders

**Comment by mahtikebab** [comment]
Thanks for the reply. It was actually a problem with how I used state in the parent react component. When clicking on a point it messaged the parent to change its state, which caused it to send new props and this caused my highcharts component to redraw (the parent is doing the AJAX reqs for the data since this data is used on other children of it aswell, meaning I do chart updating in componentWillReceiveProps). 

When using isPureConfig what would be the proper way to trigger a chart redraw? In what react lifecycle method and exactly how would it be best?

Cheers!

**Comment by kirjs** [comment]
`isPureConfig` works similarly to https://facebook.github.io/react/docs/pure-render-mixin.html
It won't update the chart if the config wasn't updated.

**Comment by kirjs** [comment]
I'm closing the issue, feel free to reopen it if if you need further help

**Comment by olegafx** [comment]
What's the correct way to redraw chart with a new data using `isPureConfig`? I tried to use `setOptions`, `redraw` and `series[0].setData`, but I got nothing useful. And where my highcharts config should live?

Ex. an app where we'are changing select value and redrawing new data on the same chart.

**Comment by olegafx** [comment]
@kirjs I couldn't make it work. Config is in state and `isPureConfig` option is used. Could you help me?

**Comment by kirjs** [comment]
Hi Oleg, the config you're passing should be a reference to a object different from the original one. 
It's best done with some immutable library, or you could deep clone the object.

**Comment by olegafx** [comment]
@kirjs oh, I was using deep cloning in a wrong place. My fault… Thanks for your response and your work :+1:

**Comment by kirjs** [comment]
No worries, good luck with your project

**Comment by nixsurya** [comment]
Is there a known issue if props of the parent changes and I re-render Treemap or Heatmap. 

There is no issue while re-rendering a simple line chart. 
The issue I see is TypeError: Cannot read property 'data classes' of undefined.

**Comment by rizkiandrianto** [comment]
> Hi Oleg, the config you're passing should be a reference to a object different from the original one.
It's best done with some immutable library, or you could deep clone the object.

What do you mean different object @kirjs ? Would you give me example code to set state the config with isPureconfig ?

**Comment by olegafx** [comment]
@rizkiandrianto just use something like 'cloneDeep' from 'lodash'

Example in React:

'''
this.setState({ chart: cloneDeep(chart) })
'''
