### ISSUE TITLE
Uncaught TypeError: Cannot set property 'HighchartsAdapter' of undefined

### ISSUE THREAD

**Issue by okonet** [kirjs/react-highcharts#43]
I'm trying this example: http://kirjs.github.io/react-highcharts/ but I'm getting the JS error:

`Uncaught TypeError: Cannot set property 'HighchartsAdapter' of undefined`

I'm using webpack in my project.

**Comment by kirjs** [comment]
Hi Andrey, 
Mind sharing your webpack config?
On which stage does the error happen?

**Comment by kirjs** [comment]
I'm closing the issue, feel free to reopen it if you still need help

**Comment by okonet** [comment]
Yeah sorry I didn't answer. I basically rewrote it for my project. Also found a few issues and made some performance improvements. I'll try to find time to submit a PR
