### ISSUE TITLE
The hight can not set? why always is 400px

### ISSUE THREAD

**Issue by Carrie999** [kirjs/react-highcharts#431]
Before Submitting an issue please reproduce it in JSBin using this setup: 
http://qs.js.org/jsbin/react-highcharts?autostart

**Comment by abhi-nahi** [comment]
follow this link (https://jsfiddle.net/gh/get/library/pure/highcharts/highcharts/tree/master/samples/highcharts/chart/height/)  . has shown an example.

OR,
You  can use CSS for ".highcharts-container" class defining height of your required size.
