### ISSUE TITLE
No need to use getDOMNOde in React 0.14 

### ISSUE THREAD

**Issue by rockneurotiko** [kirjs/react-highcharts#44]
Related with #8 

Now that React 0.14 is the main release, the DOM node refs can be accessed with the DOM component. [blog patch](https://facebook.github.io/react/blog/#dom-node-refs)

Just replace `renderTo: this.refs.chart.getDOMNode()` for `renderTo: this.refs.chart` in `chartsFactory.jsx:23` :)

**Comment by kirjs** [comment]
Thanks Rock, definitely +1 on that, should be done first thing after #41

**Comment by jasongonzales23** [comment]
+1

-___- MAKE THE RED GO AWAY

**Comment by itsmepetrov** [comment]
+1

**Comment by kirjs** [comment]
This weekend I'm planning to release 2 versions of `react-highcharts`: 
1.  `react-highcharts@3.0.0`: Will be supporting React 0.13.x, with the big refactoring of #41
2.  `reach-highcharts@4.0.0` same but works with  React 0.14.x

**Comment by jasongonzales23** [comment]
Woo! The red will be gone! Thanks @kirjs!

**Comment by kirjs** [comment]
Should be fixed in v4
