### ISSUE TITLE
How to use Funnel Chart.

### ISSUE THREAD

**Issue by kenzouno1** [kirjs/react-highcharts#440]
i'm want to use Funnel chart but how to i can import Funnel module in to my component?

trying 
`import Funnel from 'highcharts/modules/funnel';` 
`Funnel(ReactHighcharts.Highcharts);`

this will show error `Error: Highcharts error #16`

**Comment by saineri** [comment]
@kenzouno1  - I am also facing the same issue. Found any solution?

**Comment by kenzouno1** [comment]
@saineri you cantry remove `node_modules` and `.lock` file and re-install. This worked for me

**Comment by saineri** [comment]
@kenzouno1  - Thanks. It worked.. :)

**Comment by kirjs** [comment]
Seems to be resolved, closing
