### ISSUE TITLE
Highcharts Bundled Path Documentation

### ISSUE THREAD

**Issue by AlanFoster** [kirjs/react-highcharts#48]
The documentation shows -

```javascript
var Highcharts = require('react-highcharts/bundle/highcharts'); // Highcharts is bundled
```

But I believe this should be -

```javascript
var Highcharts = require('react-highcharts/dist/bundle/highcharts'); // Highcharts is bundled
```

**Comment by prakhar1989** [comment]
@AlanFoster is right! Plus update the documentation with the correct path.

PS: Thanks for this kickass react component.

**Comment by kirjs** [comment]
Thanks for creating the issue. 

I've updated the docs, but I'll keep the issue open so that I can get rid of the /dist/ part in the paths

**Comment by neverfox** [comment]
The README still shows the other path.

**Comment by kirjs** [comment]
You don't need to have dist in the path anymore, the readme seems to be correct
