### ISSUE TITLE
Global Highcharts not lazily accessed as expected

### ISSUE THREAD

**Issue by AlanFoster** [kirjs/react-highcharts#49]
As an extension to #40; We are currently seeing the same warning after upgrading to v3.

From a quick investigation of https://github.com/kirjs/react-highcharts/commit/965da2b242c5d9a2a0fb9de0026283a49a1670ea#diff-06d73f0df0c20a3ee847700bbde19f74R1, I believe that this line should be 

```javascript
if (!global.Highcharts) {
```

**Comment by kirjs** [comment]
Thanks for creating the issue. 
I need a bit more context here:
What is the warning? 
And what do you mean by lazily accessing global Highcharts?

**Comment by AlanFoster** [comment]
For instance if I added this to `test/bundle.js` within the codebase, I would expect the tests to still be green -

```javascript
require('../dist/bundle/highcharts.js');
require('../dist/bundle/highstock.js');
require('../dist/bundle/highmaps.js');
```

However we get this exception -

```
➜  react-highcharts git:(v3) ✗ npm run test

> react-highcharts@2.1.0 test /Users/alanfoster/Documents/Shopkeep/js/react-highcharts
> webpack && mocha

Hash: e477f267e26df0cb4159
Version: webpack 1.12.2
Time: 1544ms
                    Asset     Size  Chunks             Chunk Names
dist/bundle/highcharts.js   545 kB    0, 3  [emitted]  bundle/highcharts
  dist/bundle/highmaps.js   572 kB       1  [emitted]  bundle/highmaps
 dist/bundle/highstock.js   687 kB       2  [emitted]  bundle/highstock
     dist/bundle/index.js   545 kB    3, 0  [emitted]  bundle/index
       dist/highcharts.js  4.33 kB       4  [emitted]  highcharts
         dist/highmaps.js  4.41 kB       5  [emitted]  highmaps
        dist/highstock.js  4.37 kB       6  [emitted]  highstock
            dist/index.js  4.33 kB       7  [emitted]  index
   [0] multi index 28 bytes {7} [built]
   [0] multi highstock 28 bytes {6} [built]
   [0] multi highmaps 28 bytes {5} [built]
   [0] multi highcharts 28 bytes {4} [built]
    + 12 hidden modules

/Users/alanfoster/Documents/Shopkeep/js/react-highcharts/dist/bundle/highstock.js:1474
			throw msg;
			^
Highcharts error #16: www.highcharts.com/errors/16
```

Let me know if any other information is needed

**Comment by kirjs** [comment]
Now when I think about it, the bundle should actually throw if Highcharts is defined already. 

Because each bundle gets a copy of highcharts into the code base, why would we want to have multiple?

**Comment by alistairjcbrown** [comment]
@kirjs Could the bundle just use the global Highcharts if it's defined already, rather than throwing an error?
The problem we've encountering is, when testing a component which uses react-highcharts, we need to "trick" it by deleting the Highcharts global after each test to prevent this error.

**Comment by kirjs** [comment]
The issue here is having a second copy of Highcharts (160kb) in the codebase which will be loaded by the browser but never used. 

What would be the use case for having more than one bundle in the codebase?

**Comment by alistairjcbrown** [comment]
@kirjs That's a good use case, and probably more common than the problem I detailed above. It makes a good argument for the "bundled" version managing the Highcharts library loading, and erroring if already loaded.

For the "non-bundled" version, that means the developer needs to pull in their own copy of Highcharts. 
Instead, how about moving the adaptor / library requires into their own files in a `library` directory?
That would allow the same Highcharts library to be used as in the bundle, but for it not be directly bundled with the code - it puts the control of loading Highcharts back into the developers hands.

So `library/highcharts.js` might look something like:

```js
module.exports = function() {
  if (global.Highcharts) {
    throw new Error('... something nicer than error 16 ...');
  }

  global.HighchartsAdapter = require('exports?HighchartsAdapter!highcharts-standalone-adapter');
  require("highcharts");
};
```

And a developer could write:

```js
require('react-highcharts/library/highcharts')();
var ReactHighcharts = require('react-highcharts');
```

Allowing the Highcharts library to be set up once, but the component to be pulled in as many times as necessary.

**Comment by kirjs** [comment]
I tried to reach out to you by email, but got no response. 

I suggest you combine one bundled version + add-ons to get the needed functionality. 

Ping me in gchat and let's discuss if you think this solution wouldn't work for some of the use cases.

**Comment by alistairjcbrown** [comment]
@kirjs Apologies, I haven't seen anything in my inbox, but it may have been been filtered out into the junk folder.
I'll take a look at this and see if there's another way to approach it - I'm happy for this issue to be closed and I'll come back to it if there's any problems. Thanks!
