### ISSUE TITLE
How do i use highcharts and highstock on the same page?

### ISSUE THREAD

**Issue by mspe87** [kirjs/react-highcharts#55]
Im unable to use highcharts and highstock on the same page. im getting error 16: 
http://www.highcharts.com/errors/16
```
Highcharts already defined in the page

This error happens the second time Highcharts or Highstock is loaded in the same page, so the Highcharts namespace is already defined. Keep in mind that the Highcharts.Chart constructor and all features of Highcharts are included in Highstock, so if you are running Chart and StockChart in combination, you only need to load the highstock.js file.
```

im using the react-highcharts libraries like this:
```javascript
var Highstock = require('react-highcharts/dist/bundle/highstock');
var Highcharts = require('react-highcharts/dist/bundle/highcharts');
```

Any ideas or is this not possible?

**Comment by mspe87** [comment]
I had been struggling with this issue all day, and 5 minutes after posting my issue i found the solution.
For other who might have the same problem, the solution is to us bundled version of highstock and non bundled version of highcharts. The non bundled version, expects highcharts to already be loaded
```javascript
var Highstocks = require('react-highcharts/dist/bundle/highstock');
var Highcharts = require('react-highcharts');
```

**Comment by kirjs** [comment]
Thanks Mads, feel free to PR a readme update if you feel this info belongs there.

**Comment by joshhornby** [comment]
@mspe87 Thanks for this, although I seem to get this error

`Error: Starting with version 3 of react-highcharts, Highcharts is not bundled by default.  use "react-highcharts/bundle/highcharts" instead, or include highcharts`

**Comment by mspe87** [comment]
@joshhornby That was the same problem i had. You need to use it like this:
```javascript
var Highstocks = require('react-highcharts/dist/bundle/highstock');
var Highcharts = require('react-highcharts');
```

And not like this:
```javascript
var Highstock = require('react-highcharts/dist/bundle/highstock');
var Highcharts = require('react-highcharts/dist/bundle/highcharts');
```

**Comment by joshhornby** [comment]
@mspe87 I was doing that, I have re-run my build and the errors seem to have code away. But of been webpack playing up!

**Comment by joshhornby** [comment]
@mspe87 I can actually confirm that this isn't a webpack caching issue. I still get the error when using the packages like you stated.

**Comment by kirjs** [comment]
Which

**Comment by joshhornby** [comment]
I am using version `5.0.2`. I still see the `dist` directory in my node modules

**Comment by kirjs** [comment]
Can you show me how exactly your code looks like?

**Comment by joshhornby** [comment]
**Highchart**

```
render() {

      let Highcharts = require('react-highcharts');
      Highcharts.Highcharts.setOptions({
        global: {
            useUTC: false
        }
      });

      return (
        <div>
          <Highcharts config={this.props.chartData} />
        </div>
      );
    };
```

**Highstock**

```
  render() {

      let Highstock = require('react-highcharts/dist/bundle/highstock');
      Highstock.Highcharts.setOptions({
        global: {
            useUTC: false
        }
      });

      return (
        <div>
          <Highstock config={this.props.chartData} />
        </div>
      );
    };

}
```

**Comment by kirjs** [comment]
That was fast. Which exact error do you get?
What's the stack trace?

**Comment by joshhornby** [comment]
![screenshot 2015-11-17 15 42 50](https://cloud.githubusercontent.com/assets/5455767/11216194/d179b72e-8d41-11e5-8a49-fb301e74c51a.png)

The odd thing is I don't get the error on every render.

**Comment by kirjs** [comment]
I think the case here is that `require('react-highcharts/dist/bundle/highstock');` should be required before `require('react-highcharts');`, because it's the one who's getting the Highcharts in the code base. 

Also try getting rid of the dist part, it should work without it.

**Comment by joshhornby** [comment]
How would this work with two separate files though? This might explain why it sometimes errors and one chart may load before another?

**Comment by kirjs** [comment]
Do  `require('react-highcharts/dist/bundle/highstock');` somewhere on the top level of the app. 
That should fix it.

**Comment by joshhornby** [comment]
Doing this throws `Highcharts error #16: www.highcharts.com/errors/16`

**Comment by kirjs** [comment]
Use non-bundled highstock in `Highstock` file

**Comment by joshhornby** [comment]
So `require('react-highcharts/highstock');`

**Comment by kirjs** [comment]
Yes, not on top level, but in highstock file

**Comment by joshhornby** [comment]
Adding `const Highcharts = require('react-highcharts/bundle/highstock');` at the top of the file seems to have fixed this. Thanks for the help @kirjs I will continue testing tomorrow. Can we leave this issue open for next 24 hours until I can 100% confirm its fixed? If so I will PR the docs.

**Comment by kirjs** [comment]
Sure, [this](https://github.com/kirjs/react-highcharts/blob/master/recipes.md) seems like a good place for the docs. 

Also this makes me want to get rid of bundles and just better document including highcharts release in the bundle in the future.

**Comment by kirjs** [comment]
I'll close it, feel free to reopen if needed
