### ISSUE TITLE
5.0.0 already published but package.json at 4.0.0

### ISSUE THREAD

**Issue by paazmaya** [kirjs/react-highcharts#57]
https://www.npmjs.com/package/react-highcharts seems to have `5.0.0` already while the `package.json` in `master` states `4.0.0`.

Would it be possible to add git tags for those versions that have been pushed to npm, in order to see what has changed?

**Comment by kirjs** [comment]
Thanks Juga, great suggestion, please take a look at the PR, and let me know if it makes sense.

**Comment by paazmaya** [comment]
Thank you, looks good to me

**Comment by kirjs** [comment]
Now all tags are pushed to github

**Comment by paazmaya** [comment]
Thank you!

Now I can do things like this https://github.com/kirjs/react-highcharts/compare/v4.0.0...v5.0.1

**Comment by kirjs** [comment]
That's awesome, thanks!
