### ISSUE TITLE
Why Highcharts.Highcharts?

### ISSUE THREAD

**Issue by justin808** [kirjs/react-highcharts#62]
```
For access to methods & properties from the Highcharts library you can use Highcharts.Highcharts. For example, the Highcharts options are available via Highcharts.Highcharts.getOptions().
```

Why the extra level?

**Comment by justin808** [comment]
Also, is how does one use highcharts-release as a peer dependency?

**Comment by kirjs** [comment]
1. First `Highcharts` is a react component, the nested one is a `Highcharts` library
2. See https://github.com/kirjs/react-highcharts/pull/61 for an example

**Comment by kirjs** [comment]
I'm closing the issue, feel free to re-open if needed

**Comment by kirjs** [comment]
In new version if the docs it's `ReactHighcharts.Highcharts` to make it more clear

**Comment by justin808** [comment]
@kirjs Thanks!
