### ISSUE TITLE
load on demand

### ISSUE THREAD

**Issue by keenwon** [kirjs/react-highcharts#65]
the `hightcharts.js` is too big. Is there any way load like this?

```javascript
var Spline = require('react-hightcharts').spline;
var Pie = require('react-hightcharts').pie;
```

**Comment by kirjs** [comment]
Hi Keenwon, this sounds more like a Highcharts issue. 
As long as they support partial loading it shouldn't be too hard to make `react-highcharts` work with it, but so far I'm not aware of that.

**Comment by keenwon** [comment]
Thanks~
