### ISSUE TITLE
unmount -> didmount, highcharts component has no any properties!

### ISSUE THREAD

**Issue by hank7444** [kirjs/react-highcharts#67]
hi @kirjs:

I use react-router to change my page,  after I went to another page and go back Chart Page, the highcharts obj's properties is gone, my code as follows:

![image](https://cloud.githubusercontent.com/assets/4727090/11386704/f52e98f6-935e-11e5-82c4-9232bae512d9.png)

and  google console log:

![image](https://cloud.githubusercontent.com/assets/4727090/11386687/aef16d28-935e-11e5-9b16-d6af136418ec.png)

![image](https://cloud.githubusercontent.com/assets/4727090/11386691/c6919444-935e-11e5-9563-c36d0de19119.png)

have any good solution?

**Comment by hank7444** [comment]
I found the problem is react didmount but highchart hasn't loaded already...
But how could I set load event?

**Comment by hank7444** [comment]
I found highchart config has init callback, it works to me, thx!

**Comment by kirjs** [comment]
Thanks, that's my favorite issue!

**Comment by hank7444** [comment]
@kirjs   By the way, I found another issue that it chart object is empty when I use websocket to boardcast 
data every second, source code like as follews:


I need to use condition for check chart is empty or not..but I don't know how is happend..

have any good idea?

![image](https://cloud.githubusercontent.com/assets/4727090/11413575/5ebe0b28-9425-11e5-91ce-75fe8b28b98e.png)


![image](https://cloud.githubusercontent.com/assets/4727090/11413571/4b3a5eee-9425-11e5-8842-6fd6c63b9942.png)


![image](https://cloud.githubusercontent.com/assets/4727090/11413549/0fccdf44-9425-11e5-9cbb-dfac19647542.png)


Every time it will be trigger twice, first I can get chart object but second trigget I can't get it.. 

![image](https://cloud.githubusercontent.com/assets/4727090/11413603/aea33d52-9425-11e5-9668-3ee89040c61e.png)

**Comment by kirjs** [comment]
Did you try using `isPureConfig`?

**Comment by hank7444** [comment]
@kirjs  not yet, let me try today :)

**Comment by hank7444** [comment]
@kirjs  it still has the same problem, Did I make the config right?

![image](https://cloud.githubusercontent.com/assets/4727090/11432809/571e24c2-94f0-11e5-98a7-c7c1819f8aa6.png)

**Comment by kirjs** [comment]
Oh, I see now, how about you keep a flag variable and set it to true if loaded?
