### ISSUE TITLE
How to update series data without rerender highchart component?

### ISSUE THREAD

**Issue by hank7444** [kirjs/react-highcharts#71]
I want to pass data from parent component, but how could I stop reinit highchart every I passed the data?

**Comment by kirjs** [comment]
Would this example help? 
https://github.com/kirjs/react-highcharts#accessing-highcharts-api-after-render

**Comment by hank7444** [comment]
I use setData(), it's worked, thx!

**Comment by arslantariq115** [comment]
@kirjs I have been banging my head on this from yesterday. Never looked at the readme. Thanks, it worked!

**Comment by JonathanDn** [comment]
The answe seems relevant only to a React project. Could anyone direct to the methods section in the API documentation? 

I simply want to change one bar data for example in a rendered 10 bar graph without a full(costly) re-render.

What methods in the API could help me do that?

**Comment by mitul-srashtasoft** [comment]
Can you have a solution for react hooks for this problem
