### ISSUE TITLE
Having trouble with highcharts-more

### ISSUE THREAD

**Issue by lmaccherone** [kirjs/react-highcharts#72]
I've tried every possible combination of imports that I can think of but no luck. Here is what I think should work:

    import Highcharts from 'highcharts-release/highcharts.src.js';
    import 'highcharts-release/highcharts-more.src.js';
    import 'highcharts-release/modules/exporting.src.js';
    import ReactHighcharts from 'react-highcharts';

**Comment by lmaccherone** [comment]
I knew as soon as I asked, I would figure it out. This worked for me:

    import ReactHighcharts from 'react-highcharts/bundle/highcharts';
    import 'highcharts-exporting';
    import 'highcharts-more';

It meant that I had to separately `npm install` highcharts-exporting and highcharts-release

**Comment by martin-svk** [comment]
Hey I have a similar problem. I want to use `highcharts-more` to display `solidgauge` graph.
If I separately install `highcharts-exporting` and `highcharts-more` and import it like @lmaccherone I get error: `HighchartsAdapter is not defined`.

What is the preffered way to get the `highcharts-more` working. Thanks

**Comment by kirjs** [comment]
Are you sure you're using the latest version of highcharts?

**Comment by lmaccherone** [comment]
@martin-svk, did you try `npm install highcharts-exporting` and `npm install highcharts-more` and use the  imports I show above?

**Comment by martin-svk** [comment]
@kirjs Yes I think I am. (version 4.2.1). @lmaccherone Yes, I did exactly this:

```javascript
import ReactHighcharts from 'react-highcharts/bundle/highcharts';
import 'highcharts-exporting';
import 'highcharts-more';
```

and got `HighchartsAdapter is not defined` error.

**Comment by kirjs** [comment]
What if you try using non-bundled version?

**Comment by martin-svk** [comment]
@kirjs As I wrote, I tried to use non-bundled `Highcharts`:

```javascript
import Highcharts from 'highcharts';
import ReactHighcharts from 'react-highcharts';
```

but got `Highcharts is not bundled by default.  use "react-highcharts/dist/bundle/highcharts" instead, or include highcharts.` error.

**Comment by kirjs** [comment]
ReachHighcharts expects global Highcharts variable, can you try setting it explicitly?

**Comment by martin-svk** [comment]
Hi, it seems to now work with ES6 `import` but I managed to get rid of `Highcharts is not bundled by default...` message with this:

```javascript
global.Highcharts = require('highcharts');
const ReactHighcharts = require('react-highcharts'); // This works
```

I can't even combine it like this:

```javascript
global.Highcharts = require('highcharts');
import ReactHighcharts from 'react-highcharts'; // This does not work
```

But I still doesnt solve my problem (which is to import `highcharts-more` to be able to use `solidgauge`). I tried:

```javascript
global.Highcharts = require('highcharts');
global.HighchartsMore = require('highcharts-more');
const ReactHighcharts = require('react-highcharts');
```

Which don't produce any error but still getting `The requested series type does not exist` Highcharts error [17](http://www.highcharts.com/errors/17). Then I tried also require `highcharts-exporing`:

```javascript
global.Highcharts = require('highcharts');
global.HighchartsMore = require('highcharts-more');
global.HighchartsExporting = require('highcharts-exporting');
const ReactHighcharts = require('react-highcharts');
```
But that fails with `HighchartsAdapter is not defined` error.

**Comment by kirjs** [comment]
This seems to be more about the modules, I created an issue in another repository: https://github.com/kirjs/publish-highcharts-modules/issues/3

**Comment by jreuning** [comment]
@lmaccherone and anyone else who comes along later -- this seems to work (with webpack, at least):

```javascript
import ReactHighcharts from 'react-highcharts/dist/bundle/highcharts'
import HighchartsMore from 'highcharts-more'
HighchartsMore(Highcharts)
```

Using the ReactHighcharts bundle automatically adds Highcharts.

**Comment by lmaccherone** [comment]
Thanks John. This is working for me:

    ReactHighcharts = require('react-highcharts/bundle/highcharts')
    require('highcharts-exporting')
    require('highcharts-more')

**Comment by laopunk** [comment]
For what it's worth, this solution works for me: 

`   HighchartsMore = require('highcharts-more')(ReactHighcharts.Highcharts)
`

**Comment by thanasis00** [comment]
> For what it's worth, this solution works for me:
> 
> HighchartsMore = require('highcharts-more')(ReactHighcharts.Highcharts)

Thank you for this answer. It worked for me, too.

**Comment by surmistry** [comment]
Here's a _VERY_ clear example of a fully working react app and highcharts-more integration into a component 🎉 🔥 💯  https://kirjs.github.io/react-highcharts/more.html

**Comment by kenkotch** [comment]
Has anyone been able to implement highcharts-more into react-native?

**Comment by Sunzhuoyi** [comment]
import * as ReactHighcharts from "react-highcharts";
import * as HighchartsMore from "highcharts/highcharts-more";
HighchartsMore(ReactHighcharts.Highcharts);

this way worked for me
