### ISSUE TITLE
How can I set global?

### ISSUE THREAD

**Issue by hank7444** [kirjs/react-highcharts#74]
like:
```
Highcharts.setOptions({
    global: {
        // timezoneOffset: +1,
        useUTC: false
    }
});
```

**Comment by kirjs** [comment]
Would below work?
```javascript
ReactHighcharts.Highcharts.setOptions({
    global: {
        // timezoneOffset: +1,
        useUTC: false
    }
});
```

**Comment by Kureev** [comment]
@hank7444 is it still relevant?

**Comment by kirjs** [comment]
I'll close this issue, feel free to reopen

**Comment by zengxiaoluan** [comment]
这样就能搞定，感谢 @kirjs 。
`
import React from 'react';
import Highcharts from 'react-highcharts';

Highcharts.Highcharts.setOptions({
    lang: {
        resetZoom: '重置'
    }
})
`

**Comment by zengxiaoluan** [comment]
这样就能搞定，感谢 @kirjs  。

`import React from 'react';
import Highcharts from 'react-highcharts';

Highcharts.Highcharts.setOptions({
    lang: {
        resetZoom: "重置"
    }
})`
