### ISSUE TITLE
Error: Cannot resolve module 'react-highcharts/modules/more'

### ISSUE THREAD

**Issue by mmollaverdi** [kirjs/react-highcharts#80]
As per the ("using react-highcharts/more example")[http://kirjs.github.io/react-highcharts/more.html] on the README, I'm requiring `react-highcharts/modules/more`, but getting the following error:

`Module not found: Error: Cannot resolve module 'react-highcharts/modules/more' in ...`

Any idea why? Has the module been moved?

**Comment by kirjs** [comment]
Just `require('highcharts-more')` I'll update the demos soon.

**Comment by mmollaverdi** [comment]
That causes this error:

`Uncaught Highcharts error #17: www.highcharts.com/errors/17`

**Comment by kirjs** [comment]
Check out the updated example

http://kirjs.github.io/react-highcharts/more.html

**Comment by kirjs** [comment]
I'll close this issue, feel free to reopen if it still does not work

**Comment by MarloweW** [comment]
Highstock not work;

```
:50 Uncaught Error: Cannot find module "react-highcharts/ReactHighstock.src"
```

**Comment by psamim** [comment]
Same issue here, cannot find Highstock. WebPack error:
```Cannot resolve module 'react-highcharts/ReactHighstock.src'```

**Comment by constmontague** [comment]
@psamim @MarloweW which version of `react-highcharts` are you using?

**Comment by aditibhatia100** [comment]
@MarloweW @psamim : Did you guys found out the solution to  this ? Even i am facing the same issue.
