### ISSUE TITLE
Can't require highstock

### ISSUE THREAD

**Issue by ehacke** [kirjs/react-highcharts#81]
So I've tried every permutation of this I can think of, and can't get it to work. Maybe I'm doing something wrong.

I just want to require/import highstock. If I clone the repo and load the demo, it works. 

However, in my project, if I install with the following commands:

```
npm install react-highcharts highcharts-release highstock-release --save
```

And then use the following (based on the aliases used in the demo):

```javascript
global.Highcharts = require("highstock-release");
var ReactHighstock = require('react-highcharts/dist/highstock');
```

I get the error:
```
Error: ReactHighstock requires highstock to be loaded
```

If I add bundle to the path and change it to this:
```javascript
global.Highcharts = require("highstock-release");
var ReactHighstock = require('react-highcharts/dist/bundle/highstock');
```

I get the following:
```
Error: React-highcharts Highstock module expects Highstock to be loaded, but looks like a different copy of Highcharts was loaded before that
```

Any combination of loading some sub-path of `highstock-release` and/or some sub-path of `react-highcharts/dist/bundle/highstock` yields the one of those two responses.

If I just want highcharts, including the following works fine:
```javascript
var ReactHighcharts = require('react-highcharts/dist/bundle/highcharts');
```

It's just highstock I have a problem with.

**Comment by kirjs** [comment]
Hi Eric, 

What if you just require the bundle?
`var ReactHighstock = require('react-highcharts/dist/highstock');`

**Comment by ehacke** [comment]
@kirjs that exact line produces:

```
ReferenceError: Highcharts is not defined
[1]     at Object.<anonymous> (/<project path>/node_modules/react-highcharts/dist/highstock.js:1:1832)
```

If I change that to:
```
var ReactHighstock = require('react-highcharts/dist/bundle/highstock');
```

I get:
```
Error: ReactHighstock requires highstock to be loaded
```

If I use this combo:
```
var ReactHighcharts = require('react-highcharts/dist/bundle/highcharts');
var ReactHighstock = require('react-highcharts/dist/bundle/highstock');
```

I get:
```
Error: React-highcharts Highstock module expects Highstock to be loaded, but looks like a different copy of Highcharts was loaded before that
```

**Comment by kirjs** [comment]
Is Highcharts loaded in your code as a global library?
What happens if you `console.log(Highcharts)` on the very first line before trying to require anything?

**Comment by ehacke** [comment]
Hmm, yeah. `console.log(Highcharts)` just gives me `undefined`.

Even if I do `global.Highcharts = require("highcharts");` first, then console log it, I get `undefined`;

I'm using https://github.com/erikras/react-redux-universal-hot-example as a base, maybe it's shimming global or something? Hmm.

**Comment by kirjs** [comment]
Try [using fakeHighcharts for node](https://github.com/kirjs/react-highcharts/blob/master/recipes.md#rendering-react-highcharts-on-node)

**Comment by kirjs** [comment]
I'll close the issue, feel free to reopen it if the solution above didn't work
