### ISSUE TITLE
Bundle is invalid when used via global export

### ISSUE THREAD

**Issue by dbkaplun** [kirjs/react-highcharts#82]
There are two problems with https://cdnjs.cloudflare.com/ajax/libs/react-highcharts/6.0.0/highcharts.src.js and https://cdnjs.cloudflare.com/ajax/libs/react-highcharts/6.0.0/highstock.src.js:

1. `root["Highcharts"] = factory(root["react"])` should be `root["Highcharts"] = factory(root["React"])`.
2. `root["Highcharts"] = factory(root["React"])` should be `root["ReactHighcharts"] = factory(root["React"])`.

These both apply to the highstock module as well, I'm not sure about the others.

**Comment by kirjs** [comment]
Thanks for the issue, I'll take a look when I have some time, or feel free to make a PR.

**Comment by kirjs** [comment]
Should be fixed by #90, feel free to reopen
