### ISSUE TITLE
Use the highcharts npm package

### ISSUE THREAD

**Issue by TorsteinHonsi** [kirjs/react-highcharts#83]
Currently this project uses highcharts-realease, highstock-release and highmaps-release. We recommend that you use the highcharts npm package, that contains charts, stock and maps.

And thanks for contributing to Highcharts!

Torstein Hønsi,
Highcharts author

**Comment by kirjs** [comment]
Hi Torstein, thanks for the issue, and great to see Highcharts improving module-wise. 

I'll take a look when I have a spare minute.
