### ISSUE TITLE
Can't mix use of index.js and more.js

### ISSUE THREAD

**Issue by kriswallsmith** [kirjs/react-highcharts#9]
If one component uses `'react-highcharts'` and another (on the same page) uses `'react-highcharts/more'` we end up loading Highcharts twice and getting [error 16][1]. I'm using Browserify. This is probably related to #4. Thanks!

[1]: http://www.highcharts.com/errors/16

**Comment by kirjs** [comment]
Hi Kris, 
Thanks for the feedback. 

Let me experiment with it around this weekend and see if I can reproduce it, and what would be the best way to fix it.

**Comment by kirjs** [comment]
`highcharts-more` actually expects global `Highcharts` variable to be there. It actually seemed pretty awkward to do that in CommonJS, so I just bundled highcharts with highcharts-more. This is why you're getting 2 versions of highcharts. 

A temporary workaround for your case would be to use `react-highcharts/more` everywhere, and never just  `react-highcharts`. 

Eventually I'm planning to make  `react-highcharts/more` rely on the global variable, this way it will be possible to include several add-ons like `more` and `3d`. It may break some existing code though.
