### ISSUE TITLE
exporting button not shown

### ISSUE THREAD

**Issue by jma7889** [kirjs/react-highcharts#92]
It's might not be a bug. But I don't know what I did wrong. The chart is shown, but export button is not. No runtime error. Do I need to do anything to make export shown on chart?

    var Highcharts = require('react-highcharts/bundle/ReactHighcharts'); // Highcharts is bundled 
    require('highcharts-exporting');
    require('highcharts-more');

I use ES6 style class. In render:

    return (
      <div>
        <Highcharts config = {configVar} />
      </div>
    );

**Comment by kirjs** [comment]
You have to pass Highcharts instance to more and exporting. 
There should be some example on highcharts website.

**Comment by jma7889** [comment]
@kirjs I tried this, but got runtime error
    require('highcharts-exporting')(Highcharts);
    require('highcharts-more')(Highcharts);

Error I got:
    Uncaught TypeError: Cannot read property 'document' of undefined

**Comment by kirjs** [comment]
Is it happening in the browser?
Which line causes the error?

**Comment by jma7889** [comment]
This is the line:

    /*
	 Highcharts JS v4.2.3 (2016-02-08)
	 Exporting module

	 (c) 2010-2016 Torstein Honsi

	 License: www.highcharts.com/license
	*/
	(function(f){typeof module==="object"&&module.exports?module.exports=f:f(Highcharts)})(function(f){var r=f.win,m=r.document,A=f.Chart,t=f.addEvent,B=f.removeEvent,C=f.fireEvent,n=f.createElement,s=f.discardElement,v=f.css,l=f.merge,i=f.each,q=f.extend,F=f.splat,G=Math.max,H=f.isTouchDevice,I=f.Renderer.prototype.symbols,y=f.getOptions(),z;q(y.lang,{printChart:"Print chart",downloadPNG:"Download PNG image",downloadJPEG:"Download JPEG image",downloadPDF:"Download PDF document",downloadSVG:"Download SVG vector image",
	contextButtonTitle:"Chart context menu"});y.navigation={menuStyle:{border:"1px solid #A0A0A0",background:"#FFFFFF",padding:"5px 0"},menuItemStyle:{padding:"0 10px",background:"none",color:"#303030",fontSize:H?"14px":"11px"},menuItemHoverStyle:{background:"#4572A5",color:"#FFFFFF"},buttonOptions:{symbolFill:"#E0E0E0",symbolSize:14,symbolStroke:"#666",symbolStrokeWidth:3,symbolX:12.5,symbolY:10.5,align:"right",buttonSpacing:3,height:22,theme:{fill:"white",stroke:"none"},verticalAlign:"top",width:24}};
	
I tried different combinations, but so far none working.

**Comment by jma7889** [comment]
I made it working, but I don't think it's the right way to do it. @kirjs please still tell me the right way.

Instead of use exporting with webpack module, I put it in my index.html file likes this
  
    <script src="http://code.highcharts.com/highcharts.js"></script>
    <script src="http://code.highcharts.com/modules/exporting.js"></script>

And in my js code, I just use 

    var Highcharts = require('react-highcharts');

Suddenly it works. But I now treat high charts as external resource and not part of the webpack build.

**Comment by kirjs** [comment]
This is a totally legit way to go, I wonder why requiring didn't work out

**Comment by kirjs** [comment]
Actually I see now, you were trying to feed them ReactHighcharts instead of Highcharts.

**Comment by jma7889** [comment]
@kirjs I see. I tried to fix that but still not working.  I npm installed highcharts and highcharts-exporting.

    // With webpack you may wish to alias this as 'highcharts-release'
    var Highcharts = require('highcharts');
    require('highcharts/modules/exporting')(Highcharts);
    var HighchartsExporting = require('highcharts-exporting');
    HighchartsExporting(Highcharts);
    // Expects that Highcharts was loaded in the code.
    var ReactHighcharts = require('react-highcharts');

Now the error is 
    
    Uncaught Error: Starting with version 3 of react-highcharts, Highcharts is not bundled by default.  please include highcharts.

**Comment by jma7889** [comment]
OK, webpack version is working now with following code. @kirjs  what is global? It seems the key to make it work.  Is that possible to use import instead of require? I tried import, it doesn't work. 

    global.Highcharts = require('highcharts');
    require('highcharts/modules/exporting')(global.Highcharts);
    var ReactHighcharts = require('react-highcharts');

@kirjs Thanks for your help, please close the issue. Now two versions both are working.

**Comment by kirjs** [comment]
No problem, glad it works. 
global is a synonym to window. 
I'm working on a newer api which would make it easier to use.

**Comment by ommyan** [comment]
@jma7889 ,

how to make working on webpack?
