### ISSUE TITLE
Issue while using highchart, highstock and highmap on same page

### ISSUE THREAD

**Issue by chetan-jadhav** [kirjs/react-highcharts#96]
#### Details
We are trying to render 2 pie chart, 3 stock charts and 1 map chart on single page and we are getting following error.

````
Uncaught Error: React-highcharts Highmaps module expects Highmaps to be loaded, but looks like a different copy of Highcharts was loaded before that
````
We are are doing as follows.
````javascript
require('react-highcharts/dist/bundle/highmaps');
require('react-highcharts/dist/bundle/highstock');
const Highcharts = require('react-highcharts');
````

If we remove 'highmaps' statement then its working file, its rendering all pie and stock chart but when we require highmap we are getting this error.

Please let us know if we are doing anything wrong here.

**Comment by kirjs** [comment]
You seem to do the right thing. 
Try renaming `Highcharts` to `ReactHighcharts`, and let me know if that would fix it.

**Comment by chetan-jadhav** [comment]
Thanks @kirjs, I tried renaming ```Highcharts``` to ```ReactHighcharts``` but getting same error. 
```
Uncaught Error: React-highcharts Highmaps module expects Highmaps to be loaded, but looks like a different copy of Highcharts was loaded before that
```

I forgot to tell you one thing, I am passing ```ReactHighcharts```  as a prop to child components and using it. But I dont think it will make any problem since other charts are working fine with this approach.

```javascript
require('react-highcharts/dist/bundle/highmaps');
require('react-highcharts/dist/bundle/highstock');
const ReactHighcharts = require('react-highcharts');

<MyChart ReactHighcharts={ReactHighcharts} />
```

```javascript
export default class MyChart extends Component {
   render(){
     const { ReactHighcharts } = this.props;
     const config = {.....}
     <ReactHighcharts config={config} />
  }
}
```

**Comment by kirjs** [comment]
I think I understand what the reason is, looks like the bundled version of `HighMaps` doesn't want to load, because it doesn't want to introduce another copy of highcharts in the codebase. 

The workaround would be to include highcharts/highmaps/highstocks in your separately (has to be a global variable) and then use non-bundled version of react-highcharts. 

I'm working on a newer api which will solve the issue, but I don't have any ETA for it yet.

**Comment by chetan-jadhav** [comment]
@kirjs thanks for reverting back on this, let me try a workaround.

**Comment by kirjs** [comment]
Hi Chetan, I updated the new version to use proper UMD format. 
You'll have to have `highcharts` installed separately, but it should fix your issue otherwise. 

Feel free to reopen if you need any hely.
